### ISSUE TITLE
Some mods that don't work with latest update v1.0.127

### ISSUE THREAD

**Issue by itzRyuji** [FluffyFishGames/AdvancedCompany#1]
**Describe the bug**
With the latest Advanced Company update, v1.0.127, MoreInterior & Huntdown mod as well as the Wheelbarrow Item in LateGameUpgrades mod, doesn't work anymore.

**To Reproduce**
1. Update Advanced Company to v1.0.127
2. Set MoreInterior Mods to Guaranteed in Config
3. Set WheelBarrow item in LateGameUpgrades mod to true
4. Enable Huntdown mod
5. Launch game

**Expected behavior**
1. With MoreInteriors Guaranteed, it should load on any map.
2. Wheelbarrow item is set at 99999 credits, but should be set to 200. (this also breaks the portable Terminal Store)
3. Huntdown should be giving a mission in chat upon landing on any moon.

**Screenshots**
![MoreInteriors Error](https://github.com/FluffyFishGames/AdvancedCompany/assets/157503040/177ab188-7be2-4b62-a4ff-f19e8534d3ea)
![HuntDown Error](https://github.com/FluffyFishGames/AdvancedCompany/assets/157503040/5bea11d1-1ff8-499d-9348-96b6cff504a7)

**Additional context**
I have not tested with previous versions; these mods were last working with v1.0.121 (except the LGU mod WheelBarrow item).

**Logfiles**

Please provide a list of all mods you have installed. 

**Code: 018d3727-d968-8880-0376-26d1976dc360** (My Company Test Build modlist)
**Dependency string list:**
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.7.6
x753-More_Suits-1.4.1
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
malco-Lategame_Upgrades-3.1.0
sunnobunno-YippeeMod-1.2.3
AllToasters-SpectateEnemies-2.2.1
FlipMods-LetMeLookDown-1.0.1
Drakorle-MoreItems-1.0.2
Verity-TooManySuits-1.0.5
Rozebud-FOV_Adjust-1.1.1
Owen3H-IntroTweaks-1.4.2
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
Jordo-NeedyCats-1.1.1
Ryokune-CompatibilityChecker-1.1.6
IntegrityChaos-Diversity-1.1.10
Rune580-LethalCompany_InputUtils-0.5.6
quackandcheese-ToggleMute-1.3.0
CTNOriginals-CrossHair-1.0.5
RATS_RND_division-firearmlicense-1.1.0
taffyko-BetterSprayPaint-2.0.1
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
SkrimpGang-AAAAAGHH-1.0.1
doggosuki-Huntdown-1.4.1
Nebulaetrix-ScanFix-1.0.3
Supremo-Hit_Haste-1.0.0
Crab_imitation-EmissiveSuits-1.0.0
Hexnet111-Excuse_me-1.0.3
Dreamweave-CompanyBuildingEnhancements-2.6.0
Spyci-CozyImprovements-1.2.2
Ozone-BepInUtils-1.2.1
Ozone-Spawnable_Store_Items-0.1.2
TanmanG-Forest_Giant_Motionsense-1.0.2
RugbugRedfern-Skinwalkers-4.0.1
Evaisa-LethalThings-0.9.4
Jamil-Corporate_Restructure-1.0.6
mattplays-HoarderBugUseItems-1.0.3
ConeCrew-Conjured_Suits-1.0.4
quackandcheese-MirrorDecor-1.3.1
Insomniax-InsomniaxCosmetics-1.2.0
Dwarggo-Fashion_Company-1.3.0
HomelessGinger-MaskedEnemyOverhaul-3.1.1
BunyaPineTree-ModelReplacementAPI-2.3.6
FoxGod-ThiccCompanyModelReplacement-2.0.1
MassiveNewCoilers-FixCentipedeLag-2023.12.7
linkoid-DissonanceLagFix-1.0.0
SpookyDookies-Spooky_Dookies_Glowsuits-1.1.8
2018-LC_API-3.4.5
TwinDimensionalProductions-CoilHeadStare-1.0.3
Piggy-JesterStompShake-1.0.8
Woecust-NoMorePush-1.0.0
ShaosilGaming-FlashlightFix-1.0.5
EliteMasterEric-Coroner-1.5.3
ZG-BetterSpec-1.1.3
FlipMods-ObjectVolumeController-1.0.4
AgentRev-ShootableMouthDogs-1.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
Zaggy1024-PathfindingLagFix-1.2.0
Glitch-NoPropShadows-1.0.1
TeamCosmic-GoldenShovel-1.1.0
Graze-ScannablePlayerItems-1.0.4
Toskan4134-LethalRegeneration-1.2.0
FlipMods-FasterItemDropship-1.2.1
Speed3559-LethalCosmetics-1.0.0
AinaVT-LethalConfig-1.3.4
Gemumoddo-LethalEmotesAPI-1.3.2
Gemumoddo-BadAssCompany-1.1.3
matsuura-HealthMetrics-1.0.2
ButteryStancakes-AccurateStaminaDisplay-1.1.1
Theronguard-Emergency_Dice-1.1.3
PotatoePet-AdvancedCompany-1.0.127
jockie-LethalExpansionCore-1.3.14
Justice69-ImmersiveScraps-1.1.3
sleepoversquad-sleepysuits-2.0.1
sunnobunno-LandMineFartReverb-1.0.3
Rocksnotch-ShovelFix-1.1.0
IAmBatby-LethalLevelLoader-1.0.7
Major_And_Skiz-MoreInteriors-1.2.1
RaspberryProgramming-NoDeathDespawn-1.0.0
stefan750-LCUltrawide-1.1.1
bigmcnugget-VanillaContentExpansion-0.1.8
Zingar-Atlas_Abyss-1.1.4
ZG-ScalingStartCredits-1.0.6
Sligili-HDLethalCompany-1.5.6
malco-SellBodies-1.1.0
Magic_Wesley-Infernis-1.5.1
Magic_Wesley-Etern-1.3.3
Magic_Wesley-Acidir-1.4.0
willis81808-LethalSettings-1.3.0
stormytuna-SellFromTerminal-1.1.0
ViViKo-BunkbedRevive-1.1.0
Hexnet111-SuitSaver-1.1.4
Boniato-Ganimedes-1.4.0
Zaggy1024-OpenBodyCams-1.0.6
LethalMoonTeam-Ether-1.6.0
BudgetAirpods-InsanityRemastered-1.1.1
Alice-ScarletDevilMansion-1.1.2
PostMortem-BetterLightning-1.0.3
scoopy-Scoopys_Variety_Mod-0.6.5
HolographicWings-LethalExpansion-1.3.22
RedHuskyStudios-USC_Vortex-1.0.5
PC-FireExitFlip-1.0.0
Ceelery-Kast-1.0.3
LethalMatt-Outpost_31-1.0.6
KayNetsua-E_Gypt_Moon-2.0.11
Zingar-SecretLabs-3.3.4
CTMods-ChatCommands-1.1.7

**Comment by FluffyFishGames** [comment]
Insufficient logs. 1.0.128 should fix most of your problems tho.
