### ISSUE TITLE
Second moon landing doesnt work

### ISSUE THREAD

**Issue by VanilaBOI** [FluffyFishGames/AdvancedCompany#10]
**Describe the bug**
Everytime we try to land on the second moon in the session it freezes at the seed

**To Reproduce**
I haven't tested if this happen on singleplayer or lan but it's always the sencond time trying to land the moon (the first allways works)
When everyone else has left, it lands like nothing ever was wrong.
company building is an exceptiom where I as host land but the other dont.

**Expected behavior**
It landing

**Screenshots**
It doesn't freeze and we can still talk but it only starts once only the host is in the lobby

**Additional context**
We all share the same mod profile and don't join late

**Logfiles**
[log.txt](https://github.com/FluffyFishGames/AdvancedCompany/files/14043802/log.txt)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.135
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.3
AudioKnight-StarlancerMoons-0.3.0
AudioKnight-StarlancerMusic-1.1.0
AudioKnight-Starlancer-0.4.1
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
IAmBatby-LethalLevelLoader-1.0.7
Zingar-Atlas_Abyss-1.1.5
akechii-DiscountAlert-2.3.0
amnsoft-EmployeeAssignments-1.1.0
Badham_Mods-SCPFoundationDungeon-2.1.0
Confusified-KillBind-1.1.3
ButteryStancakes-AccurateStaminaDisplay-1.1.1
EchoLWS-EchosAdditionalSuits-1.4.0
F4ilS4fe-MaskTheDead-1.0.5
HomelessGinger-MaskedEnemyOverhaul-3.1.1
FlipMods-TooManyEmotes-1.8.1
Jamil-Corporate_Restructure-1.0.6
kuba6000-LC_Masked_Fix-0.0.2
Major_And_Skiz-MoreInteriors-1.2.1
matsuura-HealthMetrics-1.0.2
MoonJuice-BuyRateSettings-1.3.1
MrHydralisk-EnhancedRadarBooster-1.5.4
MrHydralisk-EnhancedLockpicker-1.1.3
NutNutty-SellTracker-1.2.1
PloufJPEG-CompanyCreatures-0.2.0
Renegades-WalkieUse-1.5.0
saint_kendrick-Lethal_Doors-1.0.3
scoopy-Scoopys_Variety_Mod-0.6.5
taffyko-BetterSprayPaint-2.0.1
ViViKo-NoSellLimit-1.0.1
Zaggy1024-OpenBodyCams-1.0.7
Asc3nt-EnhancedTZP-1.1.0
boring-CustomTranslatorCharLimit-1.0.2
ControlCompany-ControlCompany-1.1.2
EliteMasterEric-Coroner-1.5.3
Evaisa-LethalThings-0.9.4
notnotnotswipez-MoreCompany-1.7.6
Hexa-Hexas_Cosmetics-0.0.2
Jordo-NeedyCats-1.1.1
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
NotAtomicBomb-TerminalApi-1.5.1
loaforc-FacilityMeltdown-2.0.2
Ozone-BepInUtils-1.2.1
Ozone-Spawnable_Store_Items-0.1.2
ShaosilGaming-GeneralImprovements-1.0.27
Yoshify-DiscJockey-1.2.1
squirrelboydev-OopsAllFlooded-0.1.3
LethalMoonTeam-Ether-1.6.1

018d3d4f-97f2-c12c-0a8b-19951b25119c

**Comment by VanilaBOI** [comment]
[its actually working.json](https://github.com/FluffyFishGames/AdvancedCompany/files/14044039/its.actually.working.json)
I think it`s because I edited the moon weight rarities and min/max scrap

**Comment by FluffyFishGames** [comment]
I think it was due to enemies being deactivated in the enemies tab. At least thats what the log suggests. I fixed this error in 136

**Comment by FluffyFishGames** [comment]
I guess this was fixed?

**Comment by VanilaBOI** [comment]
I wasn't able to test it yet.
