### ISSUE TITLE
Portable Terminal usable while crouching

### ISSUE THREAD

**Issue by Frec100** [FluffyFishGames/AdvancedCompany#100]
The portable terminal seems to be usable while crouching, resulting in the character standing up with the terminal at it's feet outside the fixed camera's field of vision.

**To Reproduce**
1. Crouch / Sneak
2. Press the 'Portable Terminal' keybind

**Expected behavior**
Either for the terminal to be properly visible, or to be unable to open it while crouching

**Screenshots**
(Captured forcing the camera downwards)
![20240209111905_1](https://github.com/FluffyFishGames/AdvancedCompany/assets/8605482/6b818615-1ad7-4085-8936-1306abefc935)

**Logfiles**
Nothing interesting
`[Message:AdvancedCompany] Opening terminal`
`[Message:AdvancedCompany] Player 0 (local) opening terminal`

**Add a list of all of your mods**
Tested with only the following:
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.0.149

Default settings, new profile, new save.
With this setup, leaving the terminal fixes the player and makes it crouch again.

However, with one or more mods present in the following list, the bug extends to bugging the player movement permanently until restarting, causing it to move a step back everytime it stops moving:

<details> 
  <summary>Additional bug mod list</summary>
<br> | BepInEx-BepInExPack-5.4.2100
<br> | RugbugRedfern-Skinwalkers-4.0.1
<br> | x753-Mimics-2.3.2
<br> | tinyhoot-ShipLoot-1.0.0
<br> | AlexCodesGames-AdditionalContentFramework-1.0.3
<br> | AlexCodesGames-AdditionalSuits-2.0.0
<br> | Rune580-LethalCompany_InputUtils-0.6.3
<br> | sfDesat-ExpansionAssets-1.1.0
<br> | HolographicWings-LethalExpansion-1.3.36
<br> | sfDesat-Orion-1.3.0
<br> | Drakorle-MoreItems-1.0.2
<br> | Pooble-LCBetterSaves-1.7.3
<br> | FlipMods-LetMeLookDown-1.0.1
<br> | TwinDimensionalProductions-CoilHeadStare-1.0.6
<br> | sfDesat-Aquatis-1.1.1
<br> | Hexnet111-SuitSaver-1.1.4
<br> | Evaisa-HookGenPatcher-0.0.5
<br> | Evaisa-LethalLib-0.14.2
<br> | IAmBatby-LethalLevelLoader-1.1.4
<br> | scoopy-Scoopys_Variety_Mod-1.1.0
<br> | Backrooms-Backrooms-0.1.3
<br> | AinaVT-LethalConfig-1.3.4
<br> | Gemumoddo-LethalEmotesAPI-1.4.3
<br> | Gemumoddo-BadAssCompany-1.1.5
<br> | Ceelery-Kast-1.0.3
<br> | Zingar-Atlas_Abyss-1.1.6
<br> | PotatoePet-AdvancedCompany-1.0.149
<br> | jockie-LethalExpansionCore-1.3.15
<br> | sfDesat-Celest-0.2.1
<br> | AudioKnight-StarlancerMoons-0.5.4
<br> | sfDesat-ViewExtension-1.0.1
<br> | Tolian-Celestria-0.3.2
<br> | Major_And_Skiz-MoreInteriors-2.2.0
<br> | Lordfirespeed-OdinSerializer-2022.11.9
<br> | xilophor-LethalNetworkAPI-2.1.4
<br> | Piggy-LC_Office-1.0.3
<br> | Hardy-LCMaxSoundsFix-1.0.0
<br> | Magic_Wesley-Wesleys_Moons-1.0.2
<br> | itsmeowdev-DoorFix-1.0.0
<br> | x753-More_Suits-1.4.1
<br> | Norman-GlowStickSuits-1.0.4
<br> | Monkeytype-HideChat-1.0.0
<br> | FlipMods-TooManyEmotes-1.8.6
<br> | Ozone-Runtime_Netcode_Patcher-0.2.5
<br> | Sligili-More_Emotes-1.3.3
<br> | HomelessGinger-MaskedEnemyOverhaul-3.1.2
<br> | LethalMoonTeam-Ether-1.6.5
<br> | LethalMatt-Outpost_31-1.1.2
<br> | KayNetsua-E_Gypt_Moon-2.0.14
<br> | Suskitech-AlwaysHearActiveWalkies-1.4.4
<br> | quackandcheese-MirrorDecor-1.3.2
<br> | Owen3H-CSync-1.0.7
<br> | NotAtomicBomb-TerminalApi-1.5.1
<br> | fivetoofive-DetailedScan-1.2.2
<br> | IntegrityChaos-Diversity-1.1.10
<br> | Evaisa-LethalThings-0.9.4
<br> | Badham_Mods-SCPFoundationDungeon-2.3.1
<br> | Zingar-SecretLabs-3.3.5
<br> | FEB-SCP_Suits-1.1.0
<br> | Verity-TooManySuits-1.0.5
<br> | mrov-LethalRichPresence-0.5.8
<br> | 5Bit-VoiceHUD-1.0.4
<br> | EladNLG-EladsHUD-1.2.1
<br> | EliteMasterEric-SlimeTamingFix-1.0.2
<br> | BlueAmulet-LCBetterClock-1.0.3
<br> | NutNutty-SellTracker-1.2.1
<br> | blink9803-DimmingFlashlights-1.0.1
<br> | ViViKo-NoSellLimit-1.0.1
<br> | NiceHairs-NuclearLib-1.0.4
<br> | NiceHairs-Symbiosis-1.0.5
<br> | Spyci-CozyImprovements-1.2.2
<br> | akechii-DiscountAlert-2.3.0
<br> | Bobbie-FixRPCLag-1.0.1
<br> | taffyko-NameplateTweaks-1.0.6
<br> | loaforc-FacilityMeltdown-2.3.0
<br> | SillySquad-TakeThatMaskOff-2.0.0
<br> | bigmcnugget-VanillaContentExpansion-0.1.8
<br> | BGN-PizzaTowerEscapeMusic-2.3.0
<br> | LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.5
<br> | Clementinise-CustomSounds-2.3.2
<br> | no00ob-LCSoundTool-1.5.1
<br> | LethalResonance-LETHALRESONANCE-4.0.6
<br> | Zaggy1024-PathfindingLagFix-1.2.1
<br> | veri-ShipWindows-1.0.6
<br> | x753-Peepers-0.9.3
<br> | Boniato-Ganimedes-1.9.0
<br> | TeamClark-TheMostLethalCUSTOMISATION-1.3.0
<br> | Gloveman23-MoonPriceDisplay-1.0.1
</details>

Mod Manager Code:
018d8d6d-d353-804e-390a-563117a5c7f6

Thanks in advance

**Comment by FluffyFishGames** [comment]
Will be fixed in 1.1.1
