### ISSUE TITLE
BetterEmotes compatiblity patch

### ISSUE THREAD

**Issue by KlutzyBubbles** [FluffyFishGames/AdvancedCompany#102]
As of BetterEmotes 1.4.3 the local and other controller are created as AnimatorOverrideController's by default which should mean the patch you have shouldn't be needed.

But regardless of if you want to keep your patch or not, it currently sends console errors for players with both advanced company and better emotes because it targets `BetterEmotes.EmotePatch` instead of `BetterEmotes.Patches.EmotePatch` (im using version `1.0.149`)

Sorry if i have double posted this, i feel like i mentioned it somewhere but i cant find where.

**Comment by FluffyFishGames** [comment]
Will be fixed in 1.1.1

**Comment by YoBii** [comment]
First observations with AC 1.1.1 and BetterEmotes 1.4.5: seems like BetterEmotes is still breaking AC's animations unless Compatibility mode is enabled in AC settings.
