### ISSUE TITLE
ACompass overlap

### ISSUE THREAD

**Issue by SergeiBabko** [FluffyFishGames/AdvancedCompany#106]
[ACompass v1.1.1](https://thunderstore.io/c/lethal-company/p/alekso56/ACompass/)

The issue lies in the basic overlap between the slots and the compass. Additionally, having a custom implementation within the Advanced Company mod would be excellent.

**Comment by FluffyFishGames** [comment]
I might add a Y offset setting for the hotbar in 1.1.1

**Comment by FluffyFishGames** [comment]
Is added for 1.1.1
