### ISSUE TITLE
Cosmetic Lights Render in First Person

### ISSUE THREAD

**Issue by nyctodarkmatter** [FluffyFishGames/AdvancedCompany#107]
**Describe the bug**
When using a cosmetic with a light (tested with a Unity Point Light), the cosmetic will successfully be removed from first person view, but the lights remain, resulting in weird lighting issues.

**To Reproduce**
1. Equip a cosmetic with a Light attached
2. Look around in first person until you see said Light

**Expected behavior**
Lights should be hidden alongside the cosmetic while in first person view.

**Screenshots**
![image_2024-02-10_170851245](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/b3c47f39-e3e7-479f-a668-da125c19a8a5)

**Additional context**
Tested separately with only AdvancedCompany and NikkisCosmeticKingdom (indev version), problem persists.
Version of my mod on Thunderstore does not include cosmetics with lights. I've attached a version of the cosmetics with lights for testing if needed. [Cosmetic file ZIP attached.](https://github.com/FluffyFishGames/AdvancedCompany/files/14230874/ror2glasseslenseslighttest.zip)

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14230880/LogOutput.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.3
Nikki-NikkisCosmeticKingdom-1.5.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
quackandcheese-MirrorDecor-1.3.2
FlipMods-TooManyEmotes-1.8.6
Pooble-LCBetterSaves-1.7.3
PotatoePet-AdvancedCompany-1.0.149

**Comment by nyctodarkmatter** [comment]
Reached out to flipf17, the guy who makes TooManyEmotes, and he also gave me a fix that he says works in his testing. Figured it might be applicable here too so here's a screenshot.

![image_2024-02-10_213812421](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/f6bfcd52-1047-4d82-8a5e-e905867fc7ad)

**Comment by FluffyFishGames** [comment]
I consider this fixed :D
