### ISSUE TITLE
Filter Persists after Disconnecting/Qutting out of Session with Controller Held and more

### ISSUE THREAD

**Issue by vermilionshadow-vk** [FluffyFishGames/AdvancedCompany#109]
**Describe the bug**
If a player were to disconnect or leave the run between the point when they got the controller and before they got back to the ship, the pixelated filter would persist on the screen. The Doom UI however does correctly disappear with the controller absent. After the player reloads/reconnects with the aforementioned bug present, if the player were to go back indoors and find a second controller to pick up, then they encounter a new bug where the player cannot be killed, but cannot move either along with the Doom UI and shotgun absent.

**To Reproduce**
1. Start/Continue a run
2. Find the controller item (for this test, I set Controller as the only possible scrap to spawn)
3. Quit out of the game or be disconnected from an online session
4. Start/Continue any save (doesn't have to be the the one you originally found the controller on)
(NOTE: I found a 2nd bug while testing to translate a post I found on the AC thread to properly report the bug)
5. Go back indoors and find a second controller
6. Pick it up and try to move and/or try to shoot (there's no shotgun nor Doom UI, the player does not take damage during this).

**Expected behavior**
Should be able to boot up the game without the pixelated filter on. 

**Screenshots**
Before picking up the controller:
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/2f9932ab-f113-42a5-902f-7ec09d614f43)

After reloading/starting a save when holding the controller and NOT getting back to the ship with it:
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/a1f60eed-f85f-4dce-860f-6f1c76f93699)

When attempting to pick up a 2nd controller to see if bringing back to the ship clears the bug:
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/60156113/c2a7dc95-ed0f-45d7-93f6-9e6d81fc5b45)

**Additional context**
As listed in the steps, all saves are affected when this bug occurs. Even saves that you didn't pick up the controller on. This issue is cleared if the player quits out of the game entirely. I actually discovered the second bug testing to see if picking up a second controller while bugged to see if I could bring it back to the ship and fix the issue, where the initial bug description describes what occurs. It should be noted that the increased enemy spawn rate does occur even with this second bugged state active.

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14233548/Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.1.0
megumin-LethalDevMode-1.0.0

**Comment by FluffyFishGames** [comment]
Will be fixed in 1.1.1
