### ISSUE TITLE
[Suggestion] Add option to make perk/XP progress unique to host's save file (i.e. don't carry XP from other saves or lobbies)

### ISSUE THREAD

**Issue by SSyl** [FluffyFishGames/AdvancedCompany#110]
I'd like there to be an option where everyone's progress is fresh/unique to a host's save file. In other words, everyone starts fresh on that save and any previous XP/perks they've gained from other saves/lobbies doesn't carry over.

The reason I think this would be a good idea to implement is that some of us play with different friend groups, some with a lot of XP and others with less so. It's not as fun when you join a friend's game who has a lot less XP than you and you're running around at 50% movement speed and multiple inventory slots, while they're having to grind up. I think it would be fun idea if we could all be forced to start at the same level, so to speak.

I believe this functionality pretty much already exists as the "Save Progress" option, except with that option your perks are reset when you don't meet the quota. What I'm proposing is you'd still keep your progress/perks after failing the quota, but it would only be tied to that unique save file and your progress from other lobbies doesn't count towards it.

I hope this makes sense. Let me know if you want me to clarify further.

**Comment by FluffyFishGames** [comment]
Might be implemented for 1.1.1 or pushed back to 1.2 with the API changes.

I fully understand what you mean. Another option I want to add is also that all players in a lobby share the same XP even if they join later.

**Comment by crestudio** [comment]
I also want to be able to start with the same XP as any other player who joined late

**Comment by Nzii3** [comment]
This would be nice.

**Comment by FluffyFishGames** [comment]
I added new functions for 1.1.2 to make this possible.
