### ISSUE TITLE
[Request] Add volume slider for Controller "effects"

### ISSUE THREAD

**Issue by ajsglist** [FluffyFishGames/AdvancedCompany#111]
I apologize if this is the wrong place to ask, but would it be possible to get a way to adjust the overall difficulty of the... Controller "easter egg" mode's volume?  I don't want to write anything particularly spoiler-y for those who haven't experience it.

I looked through the settings/configs and I don't see a way to tweak this, and I would appreciate a volume setting for the associated mode/sfx -- they're quite a bit louder than everything else in my version of Lethal at the moment.

(For what it's worth, this was an amazing surprise.  Fantastic work)

Thanks for the consideration

**Comment by FluffyFishGames** [comment]
Will probably be added in 1.1.1

**Comment by FluffyFishGames** [comment]
Is added for 1.1.1

**Comment by ajsglist** [comment]
thank you for the quick response/update

can you point me in the direction of the volume control for this?  I don't see it in the in-game menus (admittedly may have missed it) and a check of the configs didn't turn up anything

thanks again

**Comment by ajsglist** [comment]
Sorry for the confusion, I think you're referring to the general music slider?

"Added music volume slider to settings"

<details> 
  <summary>But I was asking for a specific way to configure the volume levels for the Controller item</summary>
   because the DOOM mode is significantly louder than anything else in my game 
</details>
