### ISSUE TITLE
Hosts Cannot See Cosmetics On Masked Enemies Using Mirage

### ISSUE THREAD

**Issue by Mi6kbuttface** [FluffyFishGames/AdvancedCompany#113]
**When playing with cosmetics, the Host cannot see the cosmetics on the masked enemy, meanwhile clients can.**

**To Reproduce**
1. Launch Advanced Company with cosmetic mods enabled and the "Mirage" mod on a Host and Client game.
2. Equip cosmetics on both the host and client, and pick a suit to identify them from each other.
3. Spawn or find a naturally spawning masked enemy, and view it from both the Host's perspective, and the client's perspective.
4. Host cannot see whatever cosmetics the masked enemy has equipped.

**Expected behavior**
I expected to be able to see the cosmetics on Masked enemies from both the Host and Client, but only Client games can see cosmetics matched with Masked enemies

**Screenshots**
HOST SCREENSHOT -
![image_2024-02-13_125119559](https://github.com/FluffyFishGames/AdvancedCompany/assets/71010323/dc3daf09-9c56-4cf5-b236-43176aa8cfc6)

CLIENT SCREENSHOT -
![image_2024-02-13_125147026](https://github.com/FluffyFishGames/AdvancedCompany/assets/71010323/62b7f42d-08eb-4055-a860-79c200d33805)

**Additional context**
I am only playing with AdvancedCompany and Cosmetic mods, I do not have MoreCompany or MaskedEnemyOverhaul installed. I do have Mirage installed.

**Logfiles**
Host Logs -
[LogOutputHost.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14270354/LogOutputHost.log)

Client Logs -
[LogOutputClient.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14270357/LogOutputClient.log)

**Mods Installed**

BepInEx-BepInExPack-5.4.2100
dancemoon-DanceTools-1.1.3
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.1.1
Pooble-LCBetterSaves-1.7.3
Spark_Studios-Gridian_Cosmetics-1.4.1
companyemployee-EquipmentCompany-1.3.0
PlainBen-BensCosmetics-1.2.0
PupVR-Pups_Cute_Cosmetics-1.1.5
SpookyFingas-Cute_Cosmetics-2.0.0
kuba6000-LC_Masked_Fix-0.0.2
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
qwbarch-Mirage-1.0.12
x753-More_Suits-1.4.1
Toss-TossSuits-1.0.2

**Profile Code**

018da39e-febc-7ac2-849e-7789ebfa9ca9

**Comment by YoBii** [comment]
Supposedly fixed with Mirage v1.0.13
