### ISSUE TITLE
Compatablity with custom slots unsure of all types

### ISSUE THREAD

**Issue by CatsArmy** [FluffyFishGames/AdvancedCompany#114]
from what i have observed the custom nice lil energy bar you  make for items under them in the hud (or beside them) doesnt show up for Reserved item slots that arent one of your custom slots

i havent tested this with any other custom slot adding mods nor with your extra slots ability which i would assume works as its by you so you know mod compat go brr

**Comment by FluffyFishGames** [comment]
ReservedSlots is not supported. There will be the ability to remove all inventory changes AC does with 1.1.2. This will be the only way to use ReservedSlots but it will also remove energy indicators.
