### ISSUE TITLE
When Bulletproof Vest Gets Destroyed the Weight Exists

### ISSUE THREAD

**Issue by Yumekkiko** [FluffyFishGames/AdvancedCompany#116]
**Describe the bug**
Once the bulletproof vest gets destroyed, the weight of it exists, making you weighted. You'll walk/run slower and spend much more stamina. Only dying and rejoining could reset the weight.

**To Reproduce**
Steps to reproduce the behavior, 
1. edit the start money, the damage of shotgun to bulletproof vest and spawn rate of nutcracker
2. start the game and buy some bulletproof vests
3. go inside the facility and let nutcracker shoot you
4. put on a new one once the bulletproof vest gets destroyed, and you'll see the weight exists even if it gets destroyed

**Expected behavior**
the bulletproof vest gets destroyed and disappear, so the weight should not exist.

**Screenshots**

https://github.com/FluffyFishGames/AdvancedCompany/assets/159232068/c830d56b-c9ff-4457-8677-835d9e567e4d

**Additional context**
seems that no error log was found in the log output.
There are several attempts where I died so you may want to directly go to the bottom of the log output.

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14296305/LogOutput.log)

**Add a list of all of your mods**
it's manually installed.
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.1.1

**Comment by FluffyFishGames** [comment]
Will be fixed in 1.1.2
