### ISSUE TITLE
Equipment breaks when used with HotbarPlus

### ISSUE THREAD

**Issue by ShadowVipers** [FluffyFishGames/AdvancedCompany#117]
--- Versions ---
AdvancedCompany: v1.1.1
HotbarPlus (by FlipMods): v1.5.7

--- Versions (Non-conflicting mods) ---
LCBetterSaves (by Pooble): v1.7.3
BepInExPack (by BepInEx): v5.4.2100
LethalCompany_InputUtils (by Rune580): v0.6.3

--- Expected behavior ---
1) Pick up equipment (ex: Bulletproof vest, or Vision Enhancer)
2) Left click to equip the equipment
3) Equipment is equipped

--- Actual Behavior ---
1) Pick up equipment
2) Left click to equip
3) Nothing happens, item stays in hotbar.

--- Extensiveness of my testing ---
- Tested & Verified the cause with only 5 mods active
    - AdvancedCompany
    - HotbarPlus
    - LCBetterSaves (To prevent potential corruption of my actual saves)
    - BepInExPack (Dependency)
    - LethalCompany_InputUtils (Dependency)
- Tested with the above mods while only toggling HotbarPlus to verify that it is indeed HotbarPlus which is the cause.

--- Other Remarks ---
There's an index out of bounds error that keeps flying by in the console while HotbarPlus is enabled which I'm not sure if it's related to the above mentioned issue, but I'll add it here for the sake of completeness:
<details>
<summary>The thrown errors</summary>
It just gets endlessly spammed, below are the only 2 "unique" errors that I found among the spam. Although, not sure which one came first, since the spam quickly overwrote the oldest console history. 

NOTE: These errors only start once you load into the lobby, they do not occur during initialization or in the main menu. It also occurs on a fresh save with no scrap or store bought items present in the ship.

```
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
AdvancedCompany.Patches.InventoryPatches.UpdateHotbar (HUDManager __instance) (at G:/Unity/AdvancedCompany/UpgradeCompany/Patches/InventoryPatches.cs:1067)
(wrapper dynamic-method) HUDManager.DMD<HUDManager::Update>(HUDManager)

[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
AdvancedCompany.Game.Player.UpdateInstance () (at G:/Unity/AdvancedCompany/UpgradeCompany/Game/Player.cs:673)
AdvancedCompany.Game.Player.Update () (at G:/Unity/AdvancedCompany/UpgradeCompany/Game/Player.cs:454)
AdvancedCompany.Patches.RoundManager.Update (RoundManager __instance) (at G:/Unity/AdvancedCompany/UpgradeCompany/Patches/RoundManager.cs:23)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::Update>(RoundManager)
```

</details>

Ideally, I would just disable HotbarPlus, although, it makes rapidly unloading items onto the floor very convenient (By automagically switching to a non-empty slot). ~~I haven't found an alternative mod which achieves the desired behavior.~~

If you require any additional information then let me know and I'll try to respond to the best of my ability.

Edit: I found an alternative mod which automagically switches to non-empty slots, without causing a conflict. The mod:
- "Quick_Drop" by "Nases" (Drops everything, including equipment slots)
- "ItemDropCycler" by "boxofbiscuits97" (Drops only hotbar, but requires item in hand to start) [This one is better]

**Comment by HellbornSpartan** [comment]
to add onto this, it also affects the ability to turn on and off flashlights without holding it in your hand.

**Comment by Aeniema** [comment]
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/117127021/e8fc8703-00e6-43e3-8ee9-7ee1ac57b963)

**Comment by FluffyFishGames** [comment]
HotbarPlus is in its nature incompatible.
