### ISSUE TITLE
cant start game

### ISSUE THREAD

**Issue by AnotherCrab1** [FluffyFishGames/AdvancedCompany#119]
![2024-02-17_09-09-59](https://github.com/FluffyFishGames/AdvancedCompany/assets/157810589/a4d1f8af-c912-442c-9016-8f31ad156bbd)
so i cant start game continue button is broken

**Screenshots**
![2024-02-17_09-09-36](https://github.com/FluffyFishGames/AdvancedCompany/assets/157810589/6e737f83-02fb-476c-8006-e619627e3d3f)

![Uploading 2024-02-17_09-11-39.png…]()

**Comment by Aeniema** [comment]
@AnotherCrab1 have you got a mod list or anything? The error log in the screenshot has the start of the error cut off and not included. Something broke the function of AC, could you provide further details please?

**Comment by FluffyFishGames** [comment]
Get the latest (pirated) version v49
