### ISSUE TITLE
Vulnerability caused by the use of AdvancedCompany and Lethal Company Simplified Chinese Localization together

### ISSUE THREAD

**Issue by ZengXW6** [FluffyFishGames/AdvancedCompany#124]
**Describe the bug**
After selecting a save file and entering the ship, the purchased items will turn into red blocks with question marks. This problem can occur in both single player and multiplayer games.

**To Reproduce**
1. Install these mods simultaneously and start the game using R2Modman. Then, create a new save file and set enough initial money. enter the ship.
2. Setting the Moons as a Company,start the game, waiting for the ship to land.
3. Buy some items randomly in the store and take them to the ship, Then, take off.
4. Wait for the game's auto save to complete, then exit the game and close the game process. Then use r2modman again to open the game and select the previous save file to enter. You will find that all the items you just purchased in the store have turned into red blocks with question marks

Additional context
I disabled the SweetFox-Lethal_Company_Simplified_Chinese_Localization-1.8.33 mod, and after performing the above operation again, the model of the item can be loaded. (Please note that a new save file needs to be created)

**Logfiles**
Log information when enabling the localization mod: Can't Find item 7-铲子，replace with a block.
Log information when disabling the localization mod: Found item 7-Shovel

**a list of all of my mods**
1.PotatoePet-AdvancedCompany-1.1.1
2.SweetFox-Lethal_Company_Simplified_Chinese_Localization-1.8.33
3.Rune580-LethalCompany_InputUtils-0.6.3
4.BepInEx-BepInExPack-5.4.2100

I tried to contact SweetFox and he said this is a bug that occurred on your end. I am looking forward to your reply. Finally, Wishing you a happy Chinese New Year and the best wishes for you. Thank you very much.
（As I am not very familiar with English, the above content has been machine translated. If there are any parts that are difficult to understand, please feel free to contact me at any time）

**Comment by Yumekkiko** [comment]
想暫時解決的話可以試試把AC退回1.0.149版本

**Comment by ZengXW6** [comment]
> 想暫時解決的話可以試試把AC退回1.0.149版本

Thank you for taking time out of your busy schedule to answer my questions. I will try the solution you provided and reply as soon as possible.

**Comment by Yumekkiko** [comment]
我並不是AC作者啦XD只是其他玩家

**Comment by ZengXW6** [comment]
> 我並不是AC作者啦XD只是其他玩家

Anyway, thanks for your reply

**Comment by FluffyFishGames** [comment]
This is no "vulnerability".

Will be fixed in 1.1.2

Problem is the translator mods naive approach of replacing original game values instead of translating text when its added to UI components only.
