### ISSUE TITLE
When disabling equipment, boots icon still remains.

### ISSUE THREAD

**Issue by elihamster** [FluffyFishGames/AdvancedCompany#125]
**Describe the bug**
When disabling added equipment like rocket boots, tactical helmet, etc. No matter what the boots icon remains at the bottom right. 
**To Reproduce**
Steps to reproduce the behavior: Disable all equipment added as "QoL" one-by-one in items right before creating a lobby under the "items" tab, icon remains in game as if I can equip the items still.

**Comment by Yumekkiko** [comment]
You may just miss "Light Shoes" under the scrap list

**Comment by Aeniema** [comment]
As said, yeah Light Shoes for Boot Slot and Bunny Ears for Head Slot. <3

**Comment by FluffyFishGames** [comment]
Exactly :)
