### ISSUE TITLE
Incompatibility: FlashlightToggle & ReservedSlots

### ISSUE THREAD

**Issue by Nzii3** [FluffyFishGames/AdvancedCompany#126]
AdvancedCompany Version: latest
Both FlashlightToggle and ReservedSlots get overwritten by AdvancedCompany. I understand why for ReservedSlots, so how can I disable the hot bar entirely so the reserved slots show up? I don’t have any of the stuff enabled that uses that hot bar on the right. For FlashlightToggle, it just doesn’t turn on the flashlight at all but makes the sfx of it. I don’t know if I need to put  FlashlightToggle below AdvancedCompany so FlashlightToggle gets loaded after AdvancedCompany so Flashlight Toggle works? Idk how Thunderstore does the mod hierarchy.

**Comment by Aeniema** [comment]
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/117127021/cbc59aed-9181-4ed6-9e89-d25604a4370b)

**Comment by Nzii3** [comment]
@Aeniema The reserved slot for the flashlight and walkie aren’t present in AC.

**Comment by Nzii3** [comment]
@Ohio-Ohix I know but I'm talking about the reserved slots

**Comment by Aeniema** [comment]
> @Ohio-Ohix I know but I'm talking about the reserved slots

AC has similar functions that utilise AC's unique items - Helmet Lamp, Headset etc. Also Cursed Items use these slots.. Incompatibility with Reserved Slots and AC is well known and will never be addressed. AC has its own intentions for additional slots and upgrades, I am sorry.

**Comment by Nzii3** [comment]
You should add an option to disable the slots for AC and it would disable the helmet lamp and anything that uses that in a profile. I’ve seen people like AC but don’t like not having the reserved slots. On Feb 22, 2024, at 9:00 AM, Aeniema ***@***.***> wrote:﻿

@Ohio-Ohix I know but I'm talking about the reserved slots

AC has similar functions that utilise AC's unique items - Helmet Lamp, Headset etc. Also Cursed Items use these slots.. Incompatibility with Reserved Slots and AC is well known and will never be addressed. AC has its own intentions for additional slots and upgrades, I am sorry.

**Comment by TheBlackEntity** [comment]
> You should add an option to disable the slots for AC and it would disable the helmet lamp and anything that uses that in a profile. I’ve seen people like AC but don’t like not having the reserved slots. On Feb 22, 2024, at 9:00 AM, Aeniema ***@***.***> wrote:﻿ @Ohio-Ohix I know but I'm talking about the reserved slots AC has similar functions that utilise AC's unique items - Helmet Lamp, Headset etc. Also Cursed Items use these slots.. Incompatibility with Reserved Slots and AC is well known and will never be addressed. AC has its own intentions for additional slots and upgrades, I am sorry. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I mean... You technically still have the reserved slots... You just need different items for them

**Comment by Nzii3** [comment]
@TheBlackEntity No since I don't have the items I want.

**Comment by TheBlackEntity** [comment]
> @TheBlackEntity No since I don't have the items I want.

I thought you wanted a slot for flashlight and walkie?

Flashlight -> Helmet Lamp or Tactical Helmet
Walkie -> Headset or Tactical Helmet

What kind of items does Reserved Slots give you?

**Comment by FluffyFishGames** [comment]
There will be a new option in 1.1.2 removing all inventory related stuff in AC. This is the last ticket I will accept regarding ReservedSlots or this feature.

**Comment by Nzii3** [comment]
Perfect, thank you. Looking forward to the release.On Feb 24, 2024, at 9:01 AM, PotatoePet ***@***.***> wrote:﻿
There will be a new option in 1.1.2 removing all inventory related stuff in AC. This is the last ticket I will accept regarding ReservedSlots or this feature.
