### ISSUE TITLE
Re-enter the game file, and some items are replaced by question marks.

### ISSUE THREAD

**Issue by Elysiaiscute** [FluffyFishGames/AdvancedCompany#127]
Using this mod: sweet fox-lethal _ company _ simplified _ Chinese _ localization, some items are replaced with question mark blocks when exiting the game and then entering the game to read the archive.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/159444537/587f661e-bb11-40a2-b1f3-a69374467f9f)
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14341574/Player.log)

**Comment by modcrafts** [comment]
same issue, and it broke my save data

**Comment by FluffyFishGames** [comment]
Will be fixed in 1.1.2

Problem is the translator mods naive approach of replacing original game values instead of translating text when its added to UI components only.
