### ISSUE TITLE
LLL Moons Custom Pricing Not Deducting Appropriate Cost

### ISSUE THREAD

**Issue by ChooMcoo** [FluffyFishGames/AdvancedCompany#13]
**Describe the bug**
Route prices are not appropriately deducted when you set a custom price on a modded moon (I'm using LLL)

**To Reproduce**
1. Make a fresh profile with Advanced Company and some modded LLL moons
2. Boot game, and launch a new game to generate modded moon config options
3. Return to main menu and launch a game but go into the moon config sections this time
4. Hit the checkbox for moon pricing on the various modded moons and set it to whatever
5. Launch game and go to select one or more modded moons in terminal
6. Note it says the edited price in the interface but when routing it deducts the moons default cost.

**Expected behavior**
Appropriate cost should be deducted from funds

**Screenshots**
Pretty self explanatory. I can trim a video though if necessary though, which would probably be better

**Additional context**
I have replicated this issue with ONLY Advanced Company + dependencies and various LLL moons + dependencies

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14048813/Player.log)

**Add a list of all of your mods**
Profile code: 
018d3fb2-76ad-47be-89e0-a83cfb60aeba

Dependency strings:
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.136
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
IAmBatby-LethalLevelLoader-1.0.7
KayNetsua-E_Gypt_Moon-2.0.12
Zingar-Atlas_Abyss-1.1.5
Zingar-SecretLabs-3.3.4
Boniato-Ganimedes-1.5.0
AudioKnight-StarlancerMoons-0.3.0

**Comment by FluffyFishGames** [comment]
This should be fixed thanks to a LLL update.
