### ISSUE TITLE
Incompatibility: FontFixer

### ISSUE THREAD

**Issue by epicacrylic** [FluffyFishGames/AdvancedCompany#131]
Opening the portable terminal is fine, until you go to open the store, then the console is spammed with:

`[Warning: Unity Log] Unable to add the requested character to font asset [IBM 3270]'s atlas texture. Please make the texture [IBM 3270 Atlas] readable.`

The spam bogs down the game to 1 FPS unless you close out of the store

AdvancedCompany v1.1.1
FontFixer v1.0.0

**Comment by FluffyFishGames** [comment]
FontFixer shouldnt replace my fonts or add all necessary characters for my terminal to work. I will add it to the incompability list.
