### ISSUE TITLE
Custom Moons Dont Appear In The GUI config 'Moons'

### ISSUE THREAD

**Issue by SirKaplo** [FluffyFishGames/AdvancedCompany#133]
**Describe the bug**
'Custom moons do not load in the config menu 'moons'

**To Reproduce**
1. Go to 'Host'
2. Click on 'Any save'
3. Scroll down to 'Moons'
4. Click 'Continue'
5. See error

**Expected behavior**
probably an API or dll that is not working

**Screenshots**
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/160462539/20b77d17-efa8-4ea6-b18d-d1337efd61b6)
![image1](https://github.com/FluffyFishGames/AdvancedCompany/assets/160462539/f8500570-f3e0-4184-b1af-95382c7fd058)

**Additional context**
I just wanted to download some mods of moons but I couldn't and I wanted to report it

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14394471/Player.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
CatsArmy-SpaceSunShine-1.2.1
Wolf11221-SpaceShipDoor-1.0.1
AinaVT-LethalConfig-1.3.4
BunyaPineTree-ModelReplacementAPI-2.3.7
x753-More_Suits-1.4.1
FoxGod-ThiccCompanyModelReplacement-2.0.1
FlipMods-BetterStamina-1.3.2
Rune580-LethalCompany_InputUtils-0.6.3
Gemumoddo-LethalEmotesAPI-1.5.1
Gemumoddo-BadAssCompany-1.1.5
Ozone-Runtime_Netcode_Patcher-0.2.5
KlutzyBubbles-BetterEmotes-1.4.5
HolographicWings-LethalExpansion-1.3.42
TeamBridget-Peaches_Castle-1.0.41
ViViKo-BunkbedRevive-1.1.1
jockie-LethalExpansionCore-1.3.15
Rattenbonkers-TVLoader-1.1.1
SparrettCrow-Lethal_Cartoons_TV_Bundle-1.1.1
FutureSavior-Boombox_Sync_Fix-1.1.2
Steven-Custom_Boombox_Music-1.4.0
CodeEnder-Custom_Boombox_Fix-1.2.3
BubbleButtChamp-BoomboxJam-1.0.6
RugbugRedfern-Skinwalkers-4.0.1
no00ob-LCSoundTool-1.5.1
2018-LC_API-3.4.5
boxofbiscuits97-QuotaRollover-2.3.0
monkes_mods-JumpDelayPatch-1.0.1
sunnobunno-YippeeMod-1.2.4
CTNOriginals-CrossHair-1.1.0
sfDesat-ViewExtension-1.1.0
bctix-FPSCounter-1.3.0
Solar32-PerformanceEnhancer-1.3.6
Verity-TooManySuits-1.0.5
pattyjogal-LethalSuits-0.1.0
Robotec10-Essential_Suit_Colors-1.1.0
anormaltwig-LateCompany-1.0.11
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
AinaVT-YippeeScrap-1.0.7
Lethal_D_Company-Lethal_D_Fruits-1.0.0
NomnomAB-RollingGiant-2.5.2
MegaPiggy-BuyableShotgun-1.0.4
MegaPiggy-BuyableShotgunShells-1.0.5
Scintesto-Monster_Plushies-1.1.2
TwinDimensionalProductions-CoilHeadStare-1.0.8
instantcrystalhell-HellsPrivateSuits-1.0.3
NomnomAB-TurretKey-1.1.0
femboytv-LethalPosters-1.2.0
Darkbrewery-Vintage_Posters-1.0.3
RickArg-Helmet_Cameras-2.1.5
Boniato-CustomPaintings-1.1.0
femboytv-LethalPaintings-1.2.0
McDucky-LethalPaintingsSync-0.0.2
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
Clementinise-CustomSounds-2.3.2
KRILLCREW-BetterMenuMusic-2.0.0
zuttaf_team-roxysuit-0.1.2
SoraYuki-ShowAmmoCount-1.1.0
kim_bird-ShotGunMissFireFix-1.0.2
rhydiaan-NicerTeleporters-1.1.1
Piggy-ShowCapacity-1.0.9
Vulf-GokuBracken-1.5.4
Soviet_Union-Escape_The_Jester-1.0.0
Backrooms-Backrooms-0.1.3
TestAccount666-Real_Backrooms_Patch-1.1.0
Ccode_lang-SirenHead-0.6.4
BunyaPineTree-MikuModelReplacement-1.5.1
Clarity-BoomBoxOverhaul-1.0.1
Taker-CannabisCompany-1.0.3
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
qwbarch-Mirage-1.0.16
KawaiiBone-Remnants-1.0.0
BACONGUDEN-VileValuables-1.0.2
Kittenji-Maxwell_ScrapItem-1.0.1
EliteMasterEric-SlimeTamingFix-1.0.2
EliteMasterEric-GarageDoorFix-1.0.0
Simplexity-Fix_XP_Divide_By_Zero_Error-1.0.0
Glitch-RankFix-1.0.2
ViViKo-ItemClippingFix-1.1.3
ThePotato-scanForItemsFix-1.0.4
AgentRev-ShootableMouthDogs-1.0.1
kuba6000-LC_Masked_Fix-0.0.2
Hamunii-JetpackFallFix-2.0.1
Zaggy1024-NutcrackerFixes-1.2.2
ShaosilGaming-FlashlightFix-1.1.0
Dolphin2Point0-FadingFlashlights-1.0.2
Zaggy1024-PathfindingLagFix-1.2.1
Financier-GhostGirlFearReset-1.0.1
Bobbie-FixRPCLag-1.0.1
linkoid-DissonanceLagFix-1.0.0
fumiko-CullFactory-0.8.5
MassiveNewCoilers-FixCentipedeLag-2023.12.7
Hexnet111-SuitSaver-1.1.4
EliteMasterEric-Coroner-1.6.0
BatTeam-LethalFashion-1.0.6
FutureSavior-Hold_Scan_Button-1.1.1
akechii-DiscountAlert-2.3.0
taffyko-BetterSprayPaint-2.0.2
Jordo-NeedyCats-1.1.1
AboveFire-NeedyCatsCustomMoons-1.0.0
PopleZoo-BetterItemScan-3.0.1
itsmeowdev-DoorFix-1.0.0
loaforc-loaforcsSoundAPI-0.1.3
Hardy-LCMaxSoundsFix-1.1.0
LethalResonance-LETHALRESONANCE-4.1.9
Toskan4134-LethalRegeneration-1.2.0
CommanderJoJo-ThiccCoilHead-1.2.2
Cool_Team-Coilhead_Vine_Boom-1.0.0
Presti-Gambling-1.0.4
Verity-3rdPerson-1.1.0
Team_Tera-Record_Player_Take_Care-1.0.2
HydratedDragon-BetterItemHandling-1.1.0
Owen3H-CSync-1.0.8
NotAtomicBomb-TerminalApi-1.5.2
loaforc-FacilityMeltdown-2.3.0
taffyko-NameplateTweaks-1.0.6
matsuura-HealthMetrics-1.0.2
R8_Bustin-AlrightRobot-1.0.1
Azim-HoarderBud-1.0.11
Acromata-TwoHandedMod-1.0.0
randomneos_team-DioWryWorm-1.0.0
BGN-PizzaTowerEscapeMusic-2.3.0
kidkool-GlizzyEmotes-1.0.2
TeamOrnamentalFrFR-UntitledEmotesPack-1.0.1
JKR-JKR_Emotes-1.0.3
mertvybasein-NekiyManEmotes-1.1.7
FutureSavior-Ultrakill_Meltdown-1.0.4
PotatoePet-AdvancedCompany-1.1.1
IAmBatby-LethalLevelLoader-1.1.6

**Comment by SirKaplo** [comment]
idk what to do man

**Comment by YoBii** [comment]
Moons don't appear because you can't load into the game. They *would*  appear after first time doing that.

Did you try making a new save? ES3 is basically the save file format and the error in your ss suggests it can't be opened. 

Maybe try without LE and LEC. Then go from there.
Re-enable moon by moon. 

That's what I would do. Good luck

**Comment by FluffyFishGames** [comment]
Delete save files and retry. You need to load once into game for moons to show up.
