### ISSUE TITLE
Restart the game, item deactivated

### ISSUE THREAD

**Issue by sanshui330** [FluffyFishGames/AdvancedCompany#134]
Re-open the game and things change
![QQ截图20240225091328](https://github.com/FluffyFishGames/AdvancedCompany/assets/142911600/ef450dfe-1365-4069-b38b-ae2f64d3808d)

[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14394942/Player.log)

Please note: These logs will get overwritten everytime you start the game. So please get your logs right when the issue occured.

BepInEx-BepInExPack-5.4.2100
Evaisa-HookGenPatcher-0.0.5
Rune580-LethalCompany_InputUtils-0.6.3
Evaisa-LethalLib-0.14.2
x753-More_Suits-1.4.1
GirlDevSquad-More_Suits_Gamer_Server-1.0.0
notnotnotswipez-MoreCompany-1.8.1
Azim-LethalPresents-1.0.4
Evaisa-LethalThings-0.9.4
HomelessGinger-MaskedEnemyOverhaul-3.1.2
x753-Mimics-2.4.1
RugbugRedfern-Skinwalkers-4.0.1
FutureSavior-Boombox_Sync_Fix-1.1.2
Steven-Custom_Boombox_Music-1.4.0
Mhz-DisableUnityLogs-1.0.0
EladNLG-EladsHUD-1.2.1
Sv_Matt-HideModList-1.0.1
Rocksnotch-IncreasedDeadlines-1.0.0
claymor_wan-Lethal_Ranking-0.6.5
Fredolx-MeteoMultiplier-1.1.3
Sligili-More_Emotes-1.3.3
Drakorle-MoreItems-1.0.2
Silvision-PaintColorSwitch-1.0.0
NutNutty-SellTracker-1.2.1
anormaltwig-LateCompany-1.0.11
ficcialfaint-Spectator_Voice_Icon_Fix-1.0.0
Rattenbonkers-Teleporter_Cooldown_Reset-1.0.1
NotAtomicBomb-TerminalApi-1.5.2
NotAtomicBomb-Terminal_Clock-1.0.5
malco-Terminal_TP-1.0.1
KodiCraft-TermSpeak-1.1.0
5Bit-VoiceHUD-1.0.4
Frack9-DarkMist-1.3.0
tinyhoot-ShipLoot-1.0.0
Zduniusz-24HourClock-1.0.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
EliteMasterEric-GarageDoorFix-1.0.0
SalakStudios-BetterShotgunShells-1.0.2
FlipMods-ReservedItemSlotCore-1.8.17
Dreamweave-CompanyBuildingEnhancements-2.6.0
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
SZAKI-RemoteRemastered-1.0.2
ShaosilGaming-FlashlightFix-1.1.0
Vezcom-clownass_suit-1.0.0
OnePeak-Low_Budget_One_Piece_suits-0.5.1
Mhz-MoreHead-1.2.6
Stoners-SpiderManSuitV2-1.2.0
Pinta-PintoBoy-1.0.4
TheDeadSnake-Touchscreen-1.1.0
CHILLAX-ChillaxSCRAPS-0.6.0
Hotoni-TZPReworkedHealing-1.3.0
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
sluffs-jigglypuff_suit-1.6.1
TeamClark-SCP_Foundation_Suit-1.1.0
KlutzyBubbles-InfiniteEmote-1.3.3
IAmBatby-LethalLevelLoader-1.1.6
scoopy-Scoopys_Variety_Mod-1.2.0
Midge-PushCompany-1.2.0
Ozone-Runtime_Netcode_Patcher-0.2.5
HGG-JigglePhysicsPlugin-1.1.2
Zaggy1024-PathfindingLagFix-1.2.1
malco-Lategame_Upgrades-3.1.1
Verity-TooManySuits-1.0.5
Pooble-LCBetterSaves-1.7.3
kuba6000-LC_Masked_Fix-0.0.2
Norman-GlowStickSuits-1.0.4
jockie-LethalExpansionCore-1.3.15
Nuts-LethalPlushies-1.7.1
ViViKo-NoSellLimit-1.0.1
Insomniax-InsomniaxCosmetics-1.2.0
2018-LC_API-3.4.5
MonAmiral-PlayerDogModel-1.0.3
NiaNation-AbsasCosmetics-1.2.3
broiiler-inacraft_cosmetics_megapack-1.0.1
doggosuki-Huntdown-1.4.1
Ozone-NC_LC_API-0.0.5
Ozone-BepInUtils-1.2.1
Ozone-Cabinet_Item_Storage-0.0.4
FloofMods-WirelessCharging-1.0.0
FlipMods-TooManyEmotes-1.9.3
Clementinise-CustomSounds-2.3.2
Hardy-LCMaxSoundsFix-1.1.0
no00ob-LCSoundTool-1.5.1
LethalResonance-LETHALRESONANCE-4.1.7
Major_And_Skiz-MoreInteriors-2.5.0
sfDesat-ViewExtension-1.1.0
HolographicWings-LethalExpansion-1.3.41
Coppertiel-MaskedEnemyOverhaulFork-3.1.990
Zaggy1024-OpenBodyCams-1.2.6
Theronguard-Emergency_Dice-1.1.16
SweetOnion-LethalSnap-1.5.0
Owen3H-CSync-1.0.8
Alice-ScarletDevilMansion-1.2.7
jaspercreations-Scopophobia-1.1.1
Zingar-Atlas_Abyss-1.1.8
Lordfirespeed-OdinSerializer-2022.11.9
Yoshify-DiscJockey-1.2.1
Hexnet111-SuitSaver-1.1.4
rainbow137-MinecraftScraps-1.4.3
Monkeytype-HideChat-1.0.0
Norman-Lightsabers-1.1.2
sunnobunno-BonkHitSFX-1.0.5
EliteMasterEric-Coroner-1.6.0
Wyrdusk-Gwen_Scrap-1.0.4
AgentRev-ShootableMouthDogs-1.0.1
readthisifbad-SnatchinBracken-1.3.7
loaforc-FacilityMeltdown-2.3.0
SweetFox-Lethal_Company_Simplified_Chinese_Localization-1.8.33
Sligili-HDLethalCompany-1.5.6
miyang-Miyangtools-0.0.3
amnsoft-EmployeeAssignments-1.1.0
loaforc-loaforcsSoundAPI-0.1.2
Kittenji-NavMeshInCompany-1.0.1
Kittenji-Herobrine-1.2.10
Dev1A3-ScannableCodes-1.0.2
ViViKo-SquidGameSuits-1.0.1
TanmanG-Forest_Giant_Motionsense-1.0.2
AmesBoys-ImmortalSnail-0.6.2
veri-ShipWindows-1.2.0
darksnakex-DanceHealingOnShip-2.3.0
mrgrm7-LethalCasino-0.3.3
skidz-PoolRooms-0.1.15
xilophor-LethalNetworkAPI-2.1.6
willis81808-LethalSettings-1.4.0
Kesomannen-KeepItDown-1.1.1
Exverge-BetterSkinwalkers-0.1.2
sunnobunno-YippeeMod-1.2.4
BunyaPineTree-ModelReplacementAPI-2.3.7
Neyko-shamao-1.0.3
sfDesat-ExpansionAssets-1.1.0
sfDesat-Orion-1.3.0
PopleZoo-BetterItemScan-3.0.1
sfDesat-Aquatis-1.1.1
FlipMods-FasterItemDropship-1.2.1
KayNetsua-E_Gypt_Moon-2.0.15
Zingar-SecretLabs-3.3.7
MetalPipeSFX-HornMoan-2.1.0
happyfrosty-FrostySuits-1.1.12
Backrooms-Backrooms-0.1.3
Ceelery-Kast-1.0.3
PotatoePet-AdvancedCompany-1.1.1
AudioKnight-StarlancerMoons-0.5.7
boxofbiscuits97-QuotaRollover-2.3.0
MassiveNewCoilers-FixCentipedeLag-2023.12.7
Piggy-LC_Office-1.0.17
AudioKnight-StarlancerAIFix-2.0.0
Magic_Wesley-Infernis-3.1.0
Repyl-PeterGriffinHouse-3.6.5
taffyko-BetterSprayPaint-2.0.2
CTNOriginals-CrossHair-1.1.0
GhostbustingTrio-CustomFunSuits-1.8.3
happyfrosty-FrostySuits2-1.0.9
LethalMoonTeam-Ether-1.6.6

**Comment by FluffyFishGames** [comment]
This is nearly the 10th duplicate...
