### ISSUE TITLE
New XP settings prevent from loading in.

### ISSUE THREAD

**Issue by koodikas** [FluffyFishGames/AdvancedCompany#137]
**Describe the bug**
Can't load in after pressing continue on profile select. I have a custom profile that disabled some of the XP saving things. 

**To Reproduce**
Select a new save slot and in profile settings do a custom profile and from there go to "Save progress"
2. Settings to toggle '....'
Enabled: OFF, Individual XP: OFF and Reset XP: ON
Start XP: 0
3. Save profile and continue '....'
4. See error in log.
5. When you relaunch the game it complains that the save slot is corrupted. (it isn't corrupted when the new game was created with default settings)

**Expected behavior**
Game loads in. Only does that when I revert the XP section changes and then continue.

**Screenshots**
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/61784545/2cb79618-36bd-4802-a9a3-abddd5421fd9)

**Additional context**
I did disable and enable my latest mods and figured out the newest AC update and my profile XP settings were the cause.
It has to be the first load into the game when you do it with the XP settings, otherwise the game loads in but becomes corrupted when game is relaunched (if the XP settings were used).

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14397821/LogOutput.log)

The error when pressing the continue with the bug causing settings do this error:

```
[Info   : Unity Log] host button pressed
[Message:AdvancedCompany] Found steam ID: 76561198037901414
[Message:AdvancedCompany] Found username: Tahdikas
[Info   :AdvancedCompany] Loading player data for 76561198037901414 from server save file LCSaveFile3.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AdvancedCompany.Game.Player.LoadServer (System.String saveFile) (at G:/Unity/AdvancedCompany/UpgradeCompany/Game/Player.cs:1158)
AdvancedCompany.UI.LobbySetup.StartHost () (at G:/Unity/AdvancedCompany/UpgradeCompany/UI/LobbySetup.cs:102)
AdvancedCompany.UI.LobbySetup+<>c.<Initialize>b__5_0 (AdvancedCompany.Config.LobbyConfiguration configuration, System.String presetName) (at G:/Unity/AdvancedCompany/UpgradeCompany/UI/LobbySetup.cs:50)
BaseSettings`1[T].<Awake>b__33_2 () (at G:/Unity/AdvancedCompany/UpgradeCompany/Unity/BaseSettings.cs:282)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0022)
UnityEngine.UI.Button.Press () (at <17de86d66286445fa95af59fa8fa644d>:IL_001C)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0009)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0007)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()
```

**Add a list of all of your mods**
Also my mod profile code here: 018de221-aa28-cbe1-ea17-c9630e5415b4

BepInEx-BepInExPack-5.4.2100
Suskitech-AlwaysHearActiveWalkies-1.4.4
EliteMasterEric-Coroner-1.6.0
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.1.2
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
scoopy-Scoopys_Variety_Mod-1.2.0
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
taffyko-NameplateTweaks-1.0.6
5Bit-VoiceHUD-1.0.4
Spyci-CozyImprovements-1.2.2
darmuh-ghostCodes-1.5.1
Zaggy1024-PathfindingLagFix-1.2.1
itsmeowdev-DoorFix-1.0.0
Evaisa-LethalThings-0.9.4
Ozone-BepInUtils-1.2.1
Badham_Mods-SCPFoundationDungeon-3.0.0
Ozone-Spawnable_Store_Items-0.1.2
EladNLG-EladsHUD-1.2.1
kuba6000-LC_Masked_Fix-0.0.2
AinaVT-LethalConfig-1.3.4
fumiko-CullFactory-0.8.6
NomnomAB-TurretKey-1.1.0
Boniato-Ganimedes-2.1.0
Zingar-SecretLabs-3.3.7
NotAtomicBomb-TerminalApi-1.5.2
loaforc-FacilityMeltdown-2.3.0
ChocolateCookies-CookiesPresents-0.6.1
Owen3H-CSync-1.0.8
Hardy-LCMaxSoundsFix-1.1.0
SweetOnion-LethalSnap-1.5.0
x753-Peepers-0.9.6
SZAKI-EnemyFix-1.0.0
mrov-LethalRichPresence-0.5.8
Kittenji-Herobrine-1.2.10
Jordo-NeedyCats-1.1.1
Bobbie-UniTask-2.5.0
Bobbie-NAudio-2.2.2
qwbarch-BarchLib-1.0.0
qwbarch-Mirage-1.0.16
saint_kendrick-Lethal_Doors-1.0.4
Nyxchrono-DoorBreach-1.1.0
zealsprince-Malfunctions-1.5.5
x753-More_Suits-1.4.1
Lethal_Global_Occult-Lethal_Foundation_Suits-1.3.0
Yoshify-DiscJockey-1.2.1
AudioKnight-StarlancerMoons-0.5.7
AudioKnight-StarlancerAIFix-2.0.0
Kittenji-Groan_Tube_Scrap-1.0.1
SolidStone-ShockwaveDroneEnemy-0.3.0
mrgrm7-LethalCasino-0.3.5
skidz-PoolRooms-0.1.17
Kittenji-NavMeshInCompany-1.0.1
Alice-ScarletDevilMansion-1.2.9
jaspercreations-Scopophobia-1.1.1
BGN-PizzaTowerEscapeMusic-2.3.0
SillySquad-Arachnophilia-1.5.0
TMZ-LethalLootBug-1.0.3
IAmBatby-LethalLevelLoader-1.1.6
KayNetsua-E_Gypt_Moon-2.0.15
Kittenji-Dont_Touch_Me-1.2.1
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.9
sfDesat-ExpansionAssets-1.1.0
sfDesat-Aquatis-1.1.1
sfDesat-Celest-0.2.1
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.6
loaforc-loaforcsSoundAPI-0.1.3
LethalResonance-LETHALRESONANCE-4.2.2
BranchDev-BranchVanities-1.1.1
Hexnet111-SuitSaver-1.1.4
TeamClark-ODST_Suit-1.0.0
TeamClark-BigBossSuit-1.0.1
TeamClark-RustHazmatSuit-1.0.0
SylviBlossom-TerminalConflictFix-1.2.1
Solar32-PerformanceEnhancer-1.3.6
Magic_Wesley-Wesleys_Moons-2.1.3
Major_And_Skiz-MoreInteriors-2.5.0
Insomniax-InsomniaxCosmetics-1.2.0
bandaidroo-BandaidsMegaCosmetics-1.1.0
JFLR-TooManyHats-1.1.1
notnotnotswipez-MoreCompany-1.8.1
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-2.1.6
Piggy-LC_Office-1.0.20
dummy-LetTheDeadRest-1.0.0
ShaosilGaming-GeneralImprovements-1.1.9
mrov-WeatherTweaks-0.4.5

**Comment by FluffyFishGames** [comment]
Should be fixed in 1.1.3/1.1.4/1.1.5

You can find the version on my Discord. Depends on Thunderstore when it will be uploaded there.
