### ISSUE TITLE
I noticed you included the entirety of LLL by accident!

### ISSUE THREAD

**Issue by bobfreyfrediam** [FluffyFishGames/AdvancedCompany#141]
So Ive encountered a small bug where you must have copy pasted all of LLL into your mod on accident. Obviously, i understand this is a bug so its ok, just hoping to get it fixed soon so i can play the game again😊

Thanks in advance(d) for all the work you do!

**Comment by TheBlackEntity** [comment]
Not a bug, as far as I know.

It's his LLL Fork

**Comment by bobfreyfrediam** [comment]
Pretty big bug! Heres hoping for a speedy resolution

**Comment by FluffyFishGames** [comment]
I will split the LLL fork into its own mod soonish. I need to refactor the entirety of LLL tho. So give me some time to cook.

**Comment by FluffyFishGames** [comment]
Will be done in next version
