### ISSUE TITLE
Helmet lamp can't be bought from ship terminal

### ISSUE THREAD

**Issue by Regnareb** [FluffyFishGames/AdvancedCompany#142]
The helmet lamp can't be bought through the ship terminal, it can be bought through the portable terminal though.
It says "There was no object supplied with the action, or your word typed incorrectly or does not exist."

I tested this bug with a totally fresh save file with only AdvancedCompany installed and in default mode. The only thing different from default may that I have "Save on profile" activated.

(PS: It would be great to be able to disable Cursed objects)

**Comment by DHStyle541** [comment]
typing helmetlamp dont use space

**Comment by Regnareb** [comment]
> typing helmetlamp dont use space

Yeah I usually only type the 4th first letters for things I buy, but it didn't work either. I'd still count as a bug because the user can't know they should write it without a space. 
It's not because of spaces because "Zap" works for the Zap gun.

**Comment by FluffyFishGames** [comment]
If you have a mod with any item called Helmet you cant buy the lamp with "helmet lamp". I think its how the game handles the console. I could change this by adding my terminal keywords at top but that would break other mods.

So use portable terminal or "helmetlamp"

**Comment by Regnareb** [comment]
The thing is... I didn't have any other mod installed 😉
