### ISSUE TITLE
[Bug] Light Shoes throwing NRE when getting back to ship

### ISSUE THREAD

**Issue by ajsglist** [FluffyFishGames/AdvancedCompany#146]
**Describe the bug**
Returning to the ship with Light Shoes throws an NRE

**To Reproduce**
Grab Light Shoes in dungeon, return to ship

**Expected behavior**
No NRE

**Logfiles**
[light_shoes_NRE.txt](https://github.com/FluffyFishGames/AdvancedCompany/files/14455415/light_shoes_NRE.txt)

**Comment by FluffyFishGames** [comment]
Will be fixed in next version
