### ISSUE TITLE
PietSmietController, End of day, Drive error

### ISSUE THREAD

**Issue by TheNutFather** [FluffyFishGames/AdvancedCompany#148]
**Describe the bug**
PietSmietController couldn't update at the end of the day, was teleported back to the ship and didn't get "left behind" in the games terms.
Mod is referencing a G: drive while trying to update the state of the controller it seems.
Was able to drop PietSmietController after I was teleported back to the ship and continue playing but the console was spamming the error, and my state on the next moon landing made it so I was able to just go under flood water.
Player state corrected itself after leaving the facility again.

**To Reproduce**
1. Pick up PietSmietController
2. Wait until the day ends
3. Get teleported

The Error
 
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Unity.Netcode.NetworkBehaviour.__endSendClientRpc (Unity.Netcode.FastBufferWriter& bufferWriter, System.UInt32 rpcMethodId, Unity.Netcode.ClientRpcParams clientRpcParams, Unity.Netcode.RpcDelivery rpcDelivery) (at <895801699cfc4b4ab52267f31e2a4998>:IL_01DE)
EnemyAI.KillEnemyClientRpc (System.Boolean destroy) (at <af9b1eec498a45aebd42601d6ab85015>:IL_008D)
AdvancedCompany.Objects.PietSmietController.KillEnemy (EnemyAI enemy) (at G:/Unity/AdvancedCompany/UpgradeCompany/Objects/PietSmietController.cs:107)
AdvancedCompany.Objects.PietSmietController.Update () (at G:/Unity/AdvancedCompany/UpgradeCompany/Objects/PietSmietController.cs:255)

Thank you for this fantastic mod, can't imagine playing without it.

**Comment by FluffyFishGames** [comment]
Hopefully should be fixed in next version
