### ISSUE TITLE
mod hotbarplus not working

### ISSUE THREAD

**Issue by pogukGReeN** [FluffyFishGames/AdvancedCompany#149]
I downloaded advansedcompany and I had only 3 hotbar slots instead of 4. Along with this mod, I downloaded hotbarplus and put 8 slots in the configuration, I go into the game and there are only 6. I think okay, thanks for 6, but scrolling only works for 3 slots. The rest of the slots are just for decoration

**Comment by TheNutFather** [comment]
AC already lets you upgrade your hotbar to multiple slots, and is configurable to how many slots you start with. 
Read up on mods you install and their functionality to avoid problems in the future.

**Comment by pogukGReeN** [comment]
> AC already lets you upgrade your hotbar to multiple slots, and is configurable to how many slots you start with. Read up on mods you install and their functionality to avoid problems in the future.

I don't know English well, tell me in which section it is configured

**Comment by YoBii** [comment]
After selecting a save you see the lobby config / preset screen. Go to the tab **Perks**.
Look for **Inventory slots**
* **Base** field is your start amount of hotbar slots (300% = 3 hotbar slots).
* **Change** field is hotbar slots added per level in the **Carry bags** perk
* **Costs** is the cost per Level in the **Carry bags** perk. This must not have more than `10 - ( base / 100 )` levels defined.

To have 8 hotbar slots when you start and upgradable to the max if 10 via perk leveling do this:
* Change **Base** to `800%`
* Leave **Change** at `100%`
* Change **Costs** to `1000, 2000`

**Comment by FluffyFishGames** [comment]
And if you dont want AC to change the hotbar at all you can deactivate all inventory changes in Server configuration.
