### ISSUE TITLE
Standard preset + skip menu not working

### ISSUE THREAD

**Issue by GastonZx** [FluffyFishGames/AdvancedCompany#150]
As the title says, i set the variables on modpackConfig as Standard = Principal (name of my preset) and the skip = true, and while the skip does work, it doesnt use the preset as it says, i tried several ways besides just that, taking out the .json of the name, or placing in the folder of the default presets but it doesnt work anyways.

Mods: BepInEx - InputUtils - AdvancedCompany

**Comment by FluffyFishGames** [comment]
This should work now :)
