### ISSUE TITLE
Incorrect moons price

### ISSUE THREAD

**Issue by Los2tale** [FluffyFishGames/AdvancedCompany#152]
**Describe the bug**
All moon displasy as 0 cost

**To Reproduce**
1. I have AdvanceCompany V1.1.1 with Lastest LLL version then i update to lastest version of AdvanceCompany
2. Access terminal to get moons list
3. See error

**Expected behavior**
Show corrected moons price.

**Screenshots**
before
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/5574724/7f8de40a-5310-4ea0-95d9-25a0aad13f0c)

after
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/5574724/874adbe2-2994-48e3-b371-7b9c10017daa)

**Additional context**
-

**Logfiles**

[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14538193/LogOutput.log)

[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14538205/Player.log)

**Add a list of all of your mods**

Please provide a list of all mods you have installed. 

Go to Settings and select "Show dependency strings" and copy the text here.
Exporting your profile and attaching it to the issue might also help.

**Comment by jaeger-pmohrenstecher** [comment]
Will be fixed in next version but will only work with my fork ALL as LLL decided to be incompatible by pure choice.

**Comment by FluffyFishGames** [comment]
Will be fixed in next version but will only work with my fork ALL as LLL decided to be incompatible by pure choice.
