### ISSUE TITLE
quirk with mama llama's Lethal Company Enhancer

### ISSUE THREAD

**Issue by sharktemplar** [FluffyFishGames/AdvancedCompany#16]
Advanced Company v1.0.138 (and probably all future versions) causes a hang-up/softlock where no players respawn and the ship never re-enters orbit after a squad wipe IF Lethal Company Enhancer has its scrap loss setting set to anything but SAVE_NONE, as the two mods argue over who should be in charge of what scrap gets removed on a squad wipe, softlocking the game and forcing a restart that loses the whole day. 

If using Lethal Company Enhancer, always keep the eScrapProtection config setting on its default of SAVE_NONE, or all squad wipes become softlocks.

**Comment by FluffyFishGames** [comment]
Thanks, I added this to the compability page! :)
