### ISSUE TITLE
I  cant download advanced company

### ISSUE THREAD

**Issue by SashaXd** [FluffyFishGames/AdvancedCompany#160]
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/62339378/bc34118f-8401-4f8d-b5db-4e2378c48c5c)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/62339378/9df121e9-2de8-4c5e-84e5-5645cc83dd94)
How I can play with advanced company?

**Comment by DHStyle541** [comment]
you can't download. because this is developer mod have drama with discord modder

**Comment by rgmoon** [comment]
You can use fork version of R2 to download it
https://cdn.potatoepet.de/releases/3.1.47/Windows.zip

**Comment by jasonmbrown** [comment]
This is an issue for computer illiterate or even semi literate people. The entire point of a mod manager, is that you only have to download a single app. Now I gotta get them to jump through all sorts of hoops just to get the AdvancedCompany pack.

**Comment by FluffyFishGames** [comment]
You only have to download a single mod manager replacement over at https://mods.potatoepet.de :) Its the same software Thunderstore uses. Its r2modman with the ability to download my mods.
