### ISSUE TITLE
Thunderstore page is just gone? huh

### ISSUE THREAD

**Issue by CatsArmy** [FluffyFishGames/AdvancedCompany#161]
yea thought i should @FluffyFishGames about this as the entirety of your mods uploaded under PotatoePet is just gone... i tried to find the github a couple of days ago via thunderstore but i was unable to find the AC page then i got the link of the page and thunderstore found nothing. now i tried searching for your name in hopes of finding any of your mods but there is nothing...

hope this thunderstore issue/bug gets resolved unsure of whats going on and i wasnt sure if you were even aware of this issue so thought id let you know

**Comment by MPRATCH-V2** [comment]
PotatoePet made a forked version of r2modman which you can download his mods from. The download link is at the bottom of this website https://mods.potatoepet.de/

**Comment by FluffyFishGames** [comment]
Thank you @CatsArmy for your thoughts about me. I am aware of the situation and sadly Thunderstore wont prevent admins from sites to make up rules as they go and ban according to them.

So I will work on an improved ModLoader which will be 100% censorship resistant. You and others are of course invited to look at the source code over at https://github.com/FluffyFishGames/AdvancedModLoader and even maybe contribute when a program forms out of it and you feel like it :)

**Comment by bobfreyfrediam** [comment]
>be an ass
>get banned
>"MUH CENSORSHIP!!! ILL FORK YOU AS WELL!!"

**Comment by CatsArmy** [comment]
> >be an ass
> >get banned
> "MUH CENSORSHIP!!! ILL FORK YOU AS WELL!!"

Oi I am not aware of the events that caused the ban so you're going to need to be a little more describing as describing it as "be an ass" isn't that helpful in any way...

**Comment by FluffyFishGames** [comment]
I made it clear in my changelog that my copyright notice is protected by law and that removing it is unlawful. TS Lethal Company Admin saw this as a legal threat, claimed thats illegal and banned my mod. Claims in the US state they live in thats illegal, even tho their laws dont apply to TS or me. 

Tried to get Mythic into it and the official TS staff but they decided to not act as they dont want to get involved into content moderation because they think of themself like Reddit and that people will be able to create their own repositories of mods in Thunderstore sometime in the futurte (might still be years tho)

**Comment by CatsArmy** [comment]
> I made it clear in my changelog that my copyright notice is protected by law and that removing it is unlawful. TS Lethal Company Admin saw this as a legal threat, claimed thats illegal and banned my mod. Claims in the US state they live in thats illegal, even tho their laws dont apply to TS or me. 
> 
> Tried to get Mythic into it and the official TS staff but they decided to not act as they dont want to get involved into content moderation because they think of themself like Reddit and that people will be able to create their own repositories of mods in Thunderstore sometime in the futurte (might still be years tho)
> 
> EDIT: And I never was an ass to anyone who wasnt an ass to me first. Go figure. That Discord server is one of the most toxic cesspools I have ever encountered in my life.

I didn't think you had done anything nor has been an ass this whole thing seemed really weird and out of no where makes sense that somekind of moderation bs was going on.

Also I thought about trying to help out with the Advanced modloader but then I saw whatever those file types where cs.xml or some form of xml it seemed to be so I really have no idea how that whole app works

**Comment by CatsArmy** [comment]
The fact that one of the biggest and best mods suddenly just disappeared and apparently got banned too with no announcement on any server nor on the  thunderstore website seemed really weird.

I mean if I was a staff who has banned one of the biggest mods/mod makers on a platform I would have tried to make an announcement on the servers and website
The fact neither of those things happened seemed really shady

**Comment by FluffyFishGames** [comment]
Trust me, we are baffled by that reaction as well. I at least would have expected an official warning before just outright banning me for a warning in the changelog, that my copyright note is protected by law.

**Comment by FluffyFishGames** [comment]
Thunderstore Admins have published a statement after I fought for them to take a stance. Their stance is: We are the swiss and stay neutral:
https://gist.github.com/MythicManiac/591b0b643141d117e7983263e83ea49a

**Comment by CatsArmy** [comment]
> The fact that one of the biggest and best mods suddenly just disappeared and apparently got banned too with no announcement on any server nor on the  thunderstore website seemed really weird.
> 
> I mean if I was a staff who has banned one of the biggest mods/mod makers on a platform I would have tried to make an announcement on the servers and website
> The fact neither of those things happened seemed really shady

When I said no announcement I mostly meant no pings and nothing like that at least that I was able to find
