### ISSUE TITLE
[Suggestion] Add video how install mods without Thunderstore

### ISSUE THREAD

**Issue by 1MainMix1** [FluffyFishGames/AdvancedCompany#162]
I think it's a great idea to add a video tutorial on how to bypass Thunderstore and install a mod, or install a mod when you already have a ready-made build.

P.S. You've created really cool mods, it would be a shame if we lost them.

**Comment by MPRATCH-V2** [comment]
PotatoePet made a forked version of r2modman which you can download his mods from. The download link is at the bottom of this website https://mods.potatoepet.de/

**Comment by FluffyFishGames** [comment]
Correct. I created my own fork of r2modman with which you can still download AdvancedCompany. If somebody wants to make a video about how to install AdvancedCompany with Thunderstore they can of course do that :)
