### ISSUE TITLE
2 Questions for PotatoePet/AC Team

### ISSUE THREAD

**Issue by MPRATCH-V2** [FluffyFishGames/AdvancedCompany#163]
Firstly I apologize for opening an issue for this as it's obviously not an issue. Github seems to be the place where the the dev/devs are most active so I'm asking here.

1. I currently do not have AC in my modpack for the sole reason that loaforcsSoundAPI and it seem to conflict. In the logs loaforcsSoundAPI says AC is the issue but I also saw a post from PotatoePet saying some sound related mod author was blaming AC when any lobby increasing size mod was causing issues however my sound replacer of choice (LethalResonance) seems to function fine with morecompany. Is the conflict fixable? Should I wait for a fix from loaforcsSoundAPI or from AC? 

2. I would like to add a custom LC logo for my modpack. I am aware of some of the thunderstore drama but not all of it and since I have yet to use the 2 mods together I don't know how they function together in their current state. I saw some posts saying AC will close LC if the watermarkremover mod is added and other posts saying something along the lines of if the logo is changed AC will swap to a different mode and display "Powered by AC" so can I use a logo/watermark replacement mod with AC to display my modpack name? I am perfectly okay with it still saying powered by AC or something similar below the main menu logo and have no intention of removing any copyright notices

Sorry for the long read for 2 relatively straightforward questions I wanted to make myself as clear as possible.

**Comment by FluffyFishGames** [comment]
1. Sound mods should work afaik
2. You can place a Logo.png in your plugins folder to replace the logo. If you want to name it differently you can configure this in ModPack.cfg of AC. If its part of a Modpack you could upload a Mod with just the Logo.png in it.

**Comment by CatsArmy** [comment]
> Firstly I apologize for opening an issue for this as it's obviously not an issue. Github seems to be the place where the the dev/devs are most active so I'm asking here.
> 
>     1. I currently do not have AC in my modpack for the sole reason that loaforcsSoundAPI and it seem to conflict. In the logs loaforcsSoundAPI says AC is the issue but I also saw a post from PotatoePet saying some sound related mod author was blaming AC when any lobby increasing size mod was causing issues however my sound replacer of choice (LethalResonance) seems to function fine with morecompany. Is the conflict fixable? Should I wait for a fix from loaforcsSoundAPI or from AC?
> 

logs for the loaforcsSoundAPI issue i dont mind reading the logs and trying to find where the error originates

**Comment by MPRATCH-V2** [comment]
> 2. You can place a Logo.png in your plugins folder to replace the logo. If you want to name it differently you can configure this in ModPack.cfg of AC. If its part of a Modpack you could upload a Mod with just the Logo.png in it.

I had no idea it was this easy I thought you had to use a mod like watermarkremover. Now I get why you dislike the mod especially if they remove your copyright. Thanks for the help!

**Comment by MPRATCH-V2** [comment]
> logs for the loaforcsSoundAPI issue i dont mind reading the logs and trying to find where the error originates

I'll include [my log](https://pastebin.com/RCtZw1dV) in case you want to have a look yourself anyway but loaforcsSoundAPI points to [this](https://github.com/FluffyFishGames/AdvancedCompany/issues/130) already made github issue
