### ISSUE TITLE
Request for split mod/more config options

### ISSUE THREAD

**Issue by MPRATCH-V2** [FluffyFishGames/AdvancedCompany#164]
I would love to see more config options for disabling pieces of this mod or even better imo a mod release that only contains the lobby portions of AC. I reached out in your YouTube comment section about this and got a reply stating almost all features could be turned off for a mostly vanilla experience however after installing it again and searching through the configs I was unable to find everything I need to disable for AC to work well in my pack. Although I love AC in general really all I'm after from it is late joining and being able to have more than 4 people in a lobby. The other AC features just don't fit in my modpack anymore which sucks because AC has always provided me a more stable experience than more company, bigger lobbies, late company, or ship lobby. I understand if it takes a while but please consider releasing either another mod with only the lobby hosting portions or more config options to disable things like the portable terminal or upgrades system to help with compatibility with other mods.

**Comment by FluffyFishGames** [comment]
Unfortunatetely I leave modding for indefinite time due to the toxic lethal company modding community. I dont know what features you want to be able to deactivate. Many features of AC are interconnected so I can't simply split the mod without investing 100s of hours of work.
