### ISSUE TITLE
AdvancedCompany, Corporate Restructure, Emotes error

### ISSUE THREAD

**Issue by OneEyeDaruma** [FluffyFishGames/AdvancedCompany#17]
There is an error when the following mods are running:
- AdvancedCompany v1.0.138
- Lategame Upgrades v3.1.0
- Corporate Restructure v1.0.6
- IntroTweaks v1.4.2
- TooManyEmotes v1.8.1

It will cause players to have two player models which messes up emotes. Thanks for your hard work!

Modlist: 018d434e-ffba-4e83-b35d-48aba4ccd11d

**Comment by FluffyFishGames** [comment]
Please report this error either to Corporate Restructure or TooManyEmotes. It has nothing to do with AC.
