### ISSUE TITLE
Error when closing lobby

### ISSUE THREAD

**Issue by Zuploader** [FluffyFishGames/AdvancedCompany#18]
**Describe the bug**
No direct visual impact, but when closing lobby i get this error, might be linked to progression bug happening before, Tested this in LAN

**To Reproduce**
start a lobby in LAN mode, land , close the lobby

**Screenshots**
![closing lobby AC](https://github.com/FluffyFishGames/AdvancedCompany/assets/152256234/5c4b4769-6f5b-4246-ab67-eac7eb9a06a0)

**Logfiles**
Please attach log files to your issue. If this is a multiplayer specific issue please provide logs of the host and the affected clients.
[closing lobby Ac.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14060957/closing.lobby.Ac.log)

**Add a list of all of your mods**
018d446a-a31d-a4bf-dd84-0ca89b359546

**Comment by Zuploader** [comment]
Also i get this one when using HexiBetterShotgun as a client when joining a lobby in LAN
[Shotgun error.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14060963/Shotgun.error.log)

![Shotgun ovverride controller](https://github.com/FluffyFishGames/AdvancedCompany/assets/152256234/08777efb-9864-4bc1-841f-b2f494b1028c)

**Comment by FluffyFishGames** [comment]
First error is irrelevant. I added a unneeded null check for you.

Second error has nothing to do with AC at all.
