### ISSUE TITLE
MoreCompany Cosmetics are not loading in-game

### ISSUE THREAD

**Issue by Freelancerjw** [FluffyFishGames/AdvancedCompany#2]
**Describe the bug**
Using a clean R2 mod profile with just AdvancedCompany and its dependencies installed, MoreCompany's cosmetics are not loading.

**To Reproduce**
1. Launch Lethal Company with AdvancedCompany enabled. 
2. Click "AdvancedCompany settings" on main menu and navigate to "Cosmetics". No cosmetics are loaded. 
3. Host a lobby with the default AdvancedCompany settings and upon pressing Escape and "AdvancedCompany" in the menu and navigating to "Cosmetics", they are still not populated. 

**Expected behavior**
To be able to use MoreCompany's cosmetics without having the MoreCompany modded loaded in the modlist.

**Screenshots**
![Main Menu](https://github.com/FluffyFishGames/AdvancedCompany/assets/67694900/3ce34d10-3ade-4f30-b822-a07ecd231934)
![In Game Menu](https://github.com/FluffyFishGames/AdvancedCompany/assets/67694900/197f4e34-dd0d-47ea-9b70-f7c290aae0ea)

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14029775/Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.130

**Comment by Freelancerjw** [comment]
Misunderstanding on my part!

**Comment by FluffyFishGames** [comment]
You need to install MoreCompany if you want the standard MoreCompany cosmetics.
