### ISSUE TITLE
lobby dont starts

### ISSUE THREAD

**Issue by maximaxm** [FluffyFishGames/AdvancedCompany#20]
when i click to Continue button in lobby settings 
lobby dont starts and in console this error appears 

[Error  : Unity Log] MissingMethodException: Method not found: void .HostSettings..ctor(string,bool,string)
Stack trace:
AdvancedCompany.UI.LobbySetup+<>c.<Initialize>b__5_0 (AdvancedCompany.Config.LobbyConfiguration configuration, System.String presetName) (at G:/Unity/AdvancedCompany/UpgradeCompany/UI/LobbySetup.cs:48)
BaseSettings`1[T].<Awake>b__33_2 () (at G:/Unity/AdvancedCompany/UpgradeCompany/Unity/BaseSettings.cs:269)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0022)
UnityEngine.UI.Button.Press () (at <281a675b48d344e28f9941b2777fd620>:IL_001C)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <281a675b48d344e28f9941b2777fd620>:IL_0009)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <281a675b48d344e28f9941b2777fd620>:IL_0007)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <281a675b48d344e28f9941b2777fd620>:IL_0067)
UnityEngine.EventSystems.EventSystem:Update()

mods that i have:
Dancetools
Skinwalker mod
input utills
openbodycams 
lethal lib
hook gen patcher
and too many emotes

**Comment by FluffyFishGames** [comment]
Update your game to the latest version.
