### ISSUE TITLE
Late join problems

### ISSUE THREAD

**Issue by rgmoon** [FluffyFishGames/AdvancedCompany#21]
1.Player will get kick with error log
2.If player join the middle game while other players are in the moons, if the host die his charater will revive but the screen still present he is dead and unable to specture other players. Stuck at first person perspective.
3.After revive bug. The victim will see orignal model's equipment such like oxygen mask...etc. 

This is what will victim see after revive : 

![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/119419185/361684e8-337f-4595-981f-f726c9c18ca8)

After new games will look like this:
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/119419185/a3834cd9-3842-4c32-a51c-9ece38908eaa)

And specific error about 1. error:

![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/119419185/868727f9-91a6-4abf-b74f-119feeb21b4d)

Here is 1. problem's player log : 
1.player's log : [message.txt](https://github.com/FluffyFishGames/AdvancedCompany/files/14066844/message.txt)

Here's 2. and 3.(host) log:
2.'s google drive(over 25mbs :( ) : https://drive.google.com/file/d/1XwqPKriK4T1CmJ3rVlardJIRBhEEnTGj/view?usp=sharing

Hosts : [Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14066878/Player.log)

Mod list: 
[export.json](https://github.com/FluffyFishGames/AdvancedCompany/files/14066951/export.json)

**Comment by FluffyFishGames** [comment]
This problem should be fixed with 139.
