### ISSUE TITLE
Error with masked enemy overhaul

### ISSUE THREAD

**Issue by Zuploader** [FluffyFishGames/AdvancedCompany#22]
Latest Ac version and latest MaskedEnemy
Tested in Lan on bikini Moon
The enemy stay bug in this position

[masked.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14068555/masked.log)
![masked bug](https://github.com/FluffyFishGames/AdvancedCompany/assets/152256234/346f7f2e-5f2d-488e-b4a5-357acb720f7d)

profile code: 018d4736-db86-cd4a-887a-1a7b9edcfaf0

**Comment by FluffyFishGames** [comment]
This is an error with MaskedEnemyOverhaul. They should add a check for AC being present and dont apply their MC patches then.
