### ISSUE TITLE
The value multiplier isn't affecting the Apparatus value.

### ISSUE THREAD

**Issue by XenoX6080** [FluffyFishGames/AdvancedCompany#23]
**Describe the bug**
The value multiplier isn't affecting the Apparatus value, the value multiplier also isn't affecting on the beehive.

**Expected behavior**
The value multiplier should be affecting the Apparatus value, there are some mods which allows for changing the apparatus value, so making it change the custom value would be much appreciated. 
Alternative solution: A manual setting for the apparatus for individual map could be fine too.

As for the beehives, isn't really that a problem, because you can disable them, but if it would affect the value it would be great!

I would also hope that the weather multiplier would also affect the value of these two items
**Screenshots**
Apparatus value at 10% multiplier (you can see it how the multiplier changes the value of the dust pan)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/135417587/3ce5923e-2731-446e-afe1-346ee31a44e9)

The value of the beehive isn't affected by the multiplier.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/135417587/82f9c4dc-9e7f-4d05-860a-a38243d596df)

**Add a list of all of your mods**

Please provide a list of all mods you have installed. 

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.138

**Comment by FluffyFishGames** [comment]
Will be fixed in 140
