### ISSUE TITLE
Bunny Ears scrap item prevents movement in water entirely

### ISSUE THREAD

**Issue by ManaStar** [FluffyFishGames/AdvancedCompany#24]
Entering water while having bunny ears active prevents movement in water, locking the player in place until their untimely demise.

1. Go to a flooded moon.
2. Obtain Bunny Ears.
3. Hop into puddle.
4. You will notice that you can no longer jump, preventing further gameplay.

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.138
NotAtomicBomb-TerminalApi-1.5.1

**Comment by FluffyFishGames** [comment]
Will be fixed in 140
