### ISSUE TITLE
I had started playing just after I updated the mod and whenever I open the portable terminal it  is not positioned right and you cannot see the  entire thing

### ISSUE THREAD

**Issue by skiterbait64** [FluffyFishGames/AdvancedCompany#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Logfiles**
Please attach log files to your issue. If this is a multiplayer specific issue please provide logs of the host and the affected clients.

You can find the logs of the game in %appdata%/../LocalLow/ZeekerssRBLX/Lethal Company/

The log file is called "Player.log" (or just Player if you have file extensions hidden)

Please note: These logs will get overwritten everytime you start the game. So please get your logs right when the issue occured.

**Add a list of all of your mods**

Please provide a list of all mods you have installed. 

Go to Settings and select "Show dependency strings" and copy the text here.
Exporting your profile and attaching it to the issue might also help.

**Comment by FluffyFishGames** [comment]
Incomplete report.
