### ISSUE TITLE
Keys Are Always 3 Credits, No Matter The "Value"

### ISSUE THREAD

**Issue by CDSsmith** [FluffyFishGames/AdvancedCompany#27]
**Describe the bug**
Key Value Cannot Be Changed

**To Reproduce**
1. Go To 'Items' When Starting A Game
2. Click On The Box To Change The Value For "Key"
3. Start The Game
4. Key Still Has Value Of 3

**Expected behavior**
Key Value To Change

**Screenshots**
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/118001844/a88ef126-7560-4b82-b55c-927030efa2a5)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/118001844/c5c3a484-7f6e-4921-bca2-f104dc93b884)

**Additional context**
Other Scrap Values When Edited Seem To Be Halved When In Game, However That Is Likely Due To Another Mod

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14073223/Player.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
Sligili-HDLethalCompany-1.5.6
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
malco-Lategame_Upgrades-3.1.0
Evaisa-LethalThings-0.9.4
Azim-LethalPresents-1.0.4
Jordo-NeedyCats-1.1.1
Electric131-OuijaBoard-1.5.2
AinaVT-LethalConfig-1.3.4
AinaVT-YippeeScrap-1.0.5
blink9803-DimmingFlashlights-1.0.1
HolographicWings-LethalExpansion-1.3.25
2018-LC_API-3.4.5
CyanBlob-Motion_Tracker-1.0.0
OE_Tweaks-Possessed_Masks-2.0.1
Flof-MemeSoundboard-1.1.2
ViViKo-AllTheScrap-1.0.1
CTMods-KarmaForBeingAnnoying-1.1.0
CHILLAX-ChillaxSCRAPS-0.6.0
F4ilS4fe-MaskTheDead-1.0.5
PotatoePet-AdvancedCompany-1.0.138
Caigan-Tokucade_Scrap-1.5.0
ohotdog-LootableMusicTapes-1.0.1
scoopy-Scoopys_Variety_Mod-0.6.5
goblinfiend-Trophy-2.3.0
mattplays-HoarderBugUseItems-1.0.3
no00ob-LCSoundTool-1.5.0
AriDev-MaxwellPatch-1.0.0
Dafini-Dafis_Mega_Scrap_Pack_Emporium-1.12.4
01Ryan-MusicalInstruments-0.0.11
Steven-Custom_Boombox_Music-1.4.0
CodeEnder-Custom_Boombox_Fix-1.2.2
Crass-The_Custom_Boombox_Song_Pack-1.1.0
SalakStudios-BetterShotgunShells-1.0.2
CYW-DevysOQLMod-2.0.0
boring-CustomTranslatorCharLimit-1.0.2
Kittenji-Groan_Tube_Scrap-1.0.1
ZordAndCo-FunMusic-1.0.2
Nases-Quick_Drop-1.0.1
Spantle-BidenSoda-1.1.2
Clementinise-CustomSounds-2.3.2
RedHuskyStudios-JojoMasked-1.0.1
Clarity-BoomBoxOverhaul-1.0.1
nihl-NeutronStarSample-1.0.0
MarshMan-DeezNuts-0.1.0
Speakers-IndieGameScrap-1.2.0
jockie-LethalExpansionCore-1.3.15
BACONGUDEN-VileValuables-1.0.2
PTTeam-LethalStuff-1.0.0
notnotnotswipez-MoreCompany-1.7.6
Midge-PushCompany-1.2.0
Zingar-SecretLabs-3.3.4
PKY-SCP_scrap-1.0.0
Badham_Mods-SCPFoundationDungeon-2.2.0
RugbugRedfern-Skinwalkers-4.0.1
kuba6000-LC_Masked_Fix-0.0.2
HomelessGinger-MaskedEnemyOverhaul-3.1.1
BigSoda-Trolled-1.0.2
FutureSavior-Boombox_Sync_Fix-1.1.2
DaXcess-LethalCompanyVR-1.1.4
HolographicWings-LethalSDK-1.3.19
IAmBatby-LethalLevelLoader-1.0.7
Rune580-LethalCompany_InputUtils-0.6.1
Konspat-ImBoutToBlow-1.0.0
Legoking236-MinecraftSpiderMod-2.0.1
TheFluff-FairAI-1.3.1
NotAtomicBomb-TerminalApi-1.5.1
BGN-PizzaTowerEscapeMusic-2.3.0
loaforc-FacilityMeltdown-2.0.2
LethalResonance-Lethal_Resonance_THE_MELTDOWN-1.0.1
JanieUwU-SpongebobShoesSFX-1.0.1
Modmakers-JermaBracken-3.0.0
1NFERR-PhoneGuyCompanySpeech-1.0.1
LethalMoonTeam-Ether-1.6.2
Justice69-ImmersiveScraps-1.1.5
derprst-GarfieldScrap-1.0.1
Pikmanfan2002-PikminScrap-1.7.2
vassuki-Scrapmire-1.0.3
MoonJuice-RubberChicken-1.0.3
JoshPack-GameScrap-1.0.1
rainbow137-MinecraftScraps-1.4.1
SethC-RiskOfRainItems-0.2.7
Pinta-PintoBoy-1.0.4
togglemybits-Strange_Objects-1.2.3
SoupNBread-PanasonicBluRayScrap-1.0.0
SevenStudios-CapybaraScrap-1.0.0
s_nnys-RetroRobloxScrap-1.0.2
agalacticguy-GalacticsScrap-1.1.2
Wes0_0-More_Scrap-1.0.2
MistabsPoopnAsteroid-MistaBsAsteroid-1.2.2
agalacticguy-ToasterMod-1.0.0
Rattenbonkers-TVLoader-1.1.1
Flek_Peppers-Flek_Television_Videos-1.0.1
Moth_Development-ULTRAESCAPEMUSIC-1.3.1
Team_Tera-Record_Player_Take_Care-1.0.2
TryToDiveMe-CinemaWorld-1.0.2
EliteMasterEric-WackyCosmetics-2.0.0
Hexa-Hexas_Cosmetics-0.0.2
NiaNation-AbsasCosmetics-1.2.3
bandaidroo-BandaidsMegaCosmetics-1.0.0
windfave-Windfaves_cosmetics-1.4.0
Spark_Studios-Gridian_Cosmetics-1.4.1
Smxrez-SmoreCosmetics-1.5.0
aqua_dot-CompanyWardrobe-1.0.1
PuffyMods-Kick_Me-1.1.0
HGG-JigglePhysicsPlugin-1.1.2
Mhz-MoreHead-1.2.5
PuffyMods-Sims_Plumbob-1.1.0
s_nnys-RetroRobloxCosmetics-1.0.9
EricsTeam-EricsScrap_Helmet-1.1.1
nerdcat-FamousHeadCosmetics-1.0.0
J3STER-J3STERsCosmeticsFixed-1.0.0

Exported Pack (Replace Extension As Github Doesn't Support .R2Z):
[Lethal Boys_1706377833108.r2z](https://github.com/FluffyFishGames/AdvancedCompany/files/14073241/Lethal.Boys_1706377833108.r2z)

Code: 018d4c0d-c90f-7673-1b2a-999d0d2902a3

**Comment by FluffyFishGames** [comment]
Keys are spawned differently and therefore their value doesnt get applied. AC applies the value correctly but the game ignores that value. Nothing I can/want to do about that rn.
