### ISSUE TITLE
[Incompatibility] Minor issue with BetterEXP 1.2.0

### ISSUE THREAD

**Issue by YoBii** [FluffyFishGames/AdvancedCompany#28]
Minor. Just for tracking incompatibility I guess. You can add it to the list if you feel like it. 

BetterEXP new update added a stat to player notes (but it looks more like a new line on player name..?) and it will look like this on AC performance report
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/22051355/522fba17-5523-4646-ac35-dfd06b60990f)

Split from: https://github.com/Swaggies/BetterEXP/issues/5

**Comment by YoBii** [comment]
When player died
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/22051355/0f6b2274-3d7f-41c9-a9f1-be8689416d1d)

**Comment by FluffyFishGames** [comment]
Added to compability list

**Comment by Swaggies** [comment]
incompatibility fixed in BetterEXP 1.2.1.
