### ISSUE TITLE
Extra slot accessory visuals do not work well with custom player models

### ISSUE THREAD

**Issue by barretgoat** [FluffyFishGames/AdvancedCompany#29]
**Describe the bug**
When a non-standard player model is used, for example a shorter or non-humanoid creature, the visual representation of the items such as helmet attachments, the bulletproof vest, the tactical helmet, the rocket boots, and the flippers will not align with the player model and will instead follow the default crewmate rig. When nothing is equipped, a black and vaguely rectangular object will float where a standard crewmate's helmet would be.

**To Reproduce**
1. Install a non-standard player model. The model used by the group that encountered the issue is called LethalCreature.
2. Start a lobby with enough starting money to buy a tactical helmet.
3. Invite another person to the lobby.
4. Purchase the tactical helmet and let the other person wear it.
5. Observe the helmet placement.

**Expected behavior**
A client-side toggle in the mod settings that disables any visual alterations of the player model done by Advanced Company.

**Screenshots**
![snap8694](https://github.com/FluffyFishGames/AdvancedCompany/assets/86560996/0b8da7b7-5910-4353-855d-bde56a53f46e)

**Add a list of all of your mods**
Modlist code: 018d4c84-1f49-2b1f-3d59-0333d4b6025b

BepInEx-BepInExPack-5.4.2100
RickArg-Helmet_Cameras-2.1.5
tinyhoot-ShipLoot-1.0.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
malco-Lategame_Upgrades-3.1.0
Evaisa-LethalThings-0.9.4
Suskitech-AlwaysHearActiveWalkies-1.4.4
sunnobunno-YippeeMod-1.2.3
amnsoft-EmployeeAssignments-1.1.0
EliteMasterEric-Coroner-1.5.3
Rune580-LethalCompany_InputUtils-0.6.1
AllToasters-SpectateEnemies-2.2.1
FlipMods-LetMeLookDown-1.0.1
Jordo-NeedyCats-1.1.1
FutureSavior-Hold_Scan_Button-1.1.1
IAmBatby-LethalLevelLoader-1.0.7
Zingar-SecretLabs-3.3.4
atg-FreeJester-1.0.3
quackandcheese-ToggleMute-1.3.0
BunyaPineTree-ModelReplacementAPI-2.3.6
DarnHyena-LethalCreature-2.1.1
HolographicWings-LethalExpansion-1.3.25
jockie-LethalExpansionCore-1.3.15
sfDesat-Orion-1.2.3
sfDesat-ExpansionAssets-1.0.0
sfDesat-Aquatis-1.1.0
TeamBridget-Peaches_Castle-1.0.41
Ceelery-Kast-1.0.3
FireNoobsta-Ducks_Moons-1.1.3
Repyl-PeterGriffinHouse-3.6.5
quackandcheese-MinecraftTaigaMoon-1.1.1
Frostty-LC_Nuketown-1.0.0
TwinDimensionalProductions-CoilHeadStare-1.0.3
egeadam-MoreScreams-1.0.3
PotatoePet-AdvancedCompany-1.0.138
TheFluff-FairAI-1.3.1
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
Nemotoad-PortalTurrets-1.0.0
WalterMan-Portal_Turret_Models-1.0.2
Badham_Mods-SCPFoundationDungeon-2.2.0
scoopy-Scoopys_Variety_Mod-0.6.5
Frack9-DarkMist-1.3.0
raydenoir-WeepingAngels-1.1.0
EladNLG-EladsHUD-1.2.1
ake-Dust2-1.2.0
Pooble-LCBetterSaves-1.7.3
LethalMoonTeam-Ether-1.6.2
BlueAmulet-LCBetterClock-1.0.3
boxofbiscuits97-QuotaRollover-2.2.1
Parker7680-Free_Bird_Ejection-1.0.0

**Comment by FluffyFishGames** [comment]
Wont fix. Its either AC or model replacement.

**Comment by barretgoat** [comment]
> Wont fix. Its either AC equipment items or model replacement.

This is not a bug report, therefore a fix is not required.
However, this _is_ a feature suggestion, and I can't imagine a toggle for equipment mesh renderers being hard to implement.

**Comment by Strazyplus** [comment]
Ability to hide equipment shown on body with a toggle would be a highly requested feature. Big shame they won't do it.

**Comment by Zagovori** [comment]
> Wont fix. Its either AC equipment items or model replacement.

This is your mod, leaves those visual flying black part of the texture. I think the function to disable render for client, will be requested quite often. I don't know how hard it is to implement, but I hope you do change your mind.
