### ISSUE TITLE
No scrap value for client / Creating desync and game stuck

### ISSUE THREAD

**Issue by aserikor** [FluffyFishGames/AdvancedCompany#3]
**Describe the bug**
Clients can't see value of items/scrap in any situation 

**To Reproduce**
1. Go to : experimentation
2. Click on right click to scan
3.  Client see : "Value  "

**Expected behavior**
Clients are supposed to see correct value of each scrap

**Additional context**
We are creating a new file save and no client used late join function
Version 1.0130

**Logfiles**
Host and Client example attached

**Add a list of all of your mods**
[Playerclient.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14030871/Playerclient.log)
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14030874/Player.log)

Please provide a list of all mods you have installed. 

BepInEx-BepInExPack-5.4.2100
Sligili-HDLethalCompany-1.5.6
x753-Mimics-2.3.2
AlexCodesGames-AdditionalSuits-2.0.0
tinyhoot-ShipLoot-1.0.0
SirTyler-BetterTeleporter-1.2.2
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
Evaisa-LethalThings-0.9.4
Azim-LethalPresents-1.0.4
Rune580-LethalCompany_InputUtils-0.6.0
Badham_Mods-SCPFoundationDungeon-2.1.0
PotatoePet-AdvancedCompany-1.0.131
IntegrityChaos-Diversity-1.1.10
scoopy-Scoopys_Variety_Mod-0.6.5
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
Clementinise-QuickTerminalRestart-1.0.3
NomnomAB-RollingGiant-2.4.4
Coomfy-CoomfyDungeon-1.0.12
OE_Tweaks-Lucky_Dice-0.4.1
IAmBatby-LethalLevelLoader-1.0.7
notnotnotswipez-MoreCompany-1.7.6
Insomniax-InsomniaxCosmetics-1.2.0
FlipMods-TooManyEmotes-1.8.1
AlexCodesGames-AdditionalContentFramework-1.0.3
NotAtomicBomb-TerminalApi-1.5.1
Zaggy1024-PathfindingLagFix-1.2.0
Yoshify-DiscJockey-1.2.1
Major_And_Skiz-MoreInteriors-1.2.1
LethalResonance-LETHALRESONANCE-2.1.7
Alice-ScarletDevilMansion-1.1.3
SpookyFingas-Anime_Essentials-1.0.0
Spark_Studios-Gridian_Cosmetics-1.4.1

**Comment by FluffyFishGames** [comment]
Can't really replicate this issue. But found an error in the log which I've fixed. Maybe this will help.

**Comment by aserikor** [comment]
Last update fixed issue, thank for your quick fix and help :)
