### ISSUE TITLE
Animation Bug

### ISSUE THREAD

**Issue by ChaosKronorium** [FluffyFishGames/AdvancedCompany#30]
When using Badass company, mid emote if you pull out the portable terminal it breaks your characters animation for default/more emotes and it breaks your normal animations.

Steps to reproduce the behaviour:
1. load up
2. emote with Badass Company
3. press x whilst emoting
4. now its bugged

Screenshots:
![20240128173645_1](https://github.com/FluffyFishGames/AdvancedCompany/assets/58388979/7da2260e-a49e-45fe-82ea-8807c8119c9b)

![20240128173657_1](https://github.com/FluffyFishGames/AdvancedCompany/assets/58388979/0a603e21-de2d-43ad-972c-10b568593a7b)

![20240128173724_1](https://github.com/FluffyFishGames/AdvancedCompany/assets/58388979/03cfdf44-a182-444d-9115-73e2399bf7c9)

Logs:
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14075182/Player.log)

Modlist:
Sligili-HDLethalCompany-1.5.6
Zduniusz-24HourClock-1.0.0
IDFK_Game-VineBoomCoilHead-1.0.0
Joalek-Joalek_COD_Zombies_Firesale_Music_Pack-115.1.15
LethalMatt-COD_Zombies_Round_Start_Music-1.0.3
Vintys-MetalGearTurretSound-1.0.2
Rev-DoomNutcracker-1.0.2
Xylq-Dr_Livesey_Jester-1.0.0
sunnobunno-YippeeMod-1.2.3
sunnobunno-LandMineFartReverb-1.0.3
BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.4.5
notnotnotswipez-MoreCompany-1.7.6
x753-More_Suits-1.4.1
akkowo-More_suit_colors_for_more_suits-1.0.0
Midge-PushCompany-1.2.0
femboytv-LethalPosters-1.2.0
femboytv-LethalReynolds-1.2.0
femboytv-LethalPaintings-1.2.0
Sligili-More_Emotes-1.3.3
Pooble-LCBetterSaves-1.7.3
RugbugRedfern-Skinwalkers-4.0.1
matsuura-HealthMetrics-1.0.2
BlueAmulet-LCBetterClock-1.0.3
EliteMasterEric-Coroner-1.5.3
RickArg-Helmet_Cameras-2.1.5
taffyko-NameplateTweaks-1.0.6
FlipMods-LetMeLookDown-1.0.1
MassiveNewCoilers-FixCentipedeLag-2023.12.7
5Bit-VoiceHUD-1.0.4
PopleZoo-BetterItemScan-3.0.1
AllToasters-QuickRestart-1.2.0
Giltong-LethalCompanyDRP-1.3.6
ATK-ShipClock-0.9.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
steven4547466-CommandHandler-1.0.0
FlipMods-SkipToMultiplayerMenu-1.0.0
Alejo47-FasterTeleporter-1.0.2
Hexnet111-SuitSaver-1.1.4
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
Evaisa-LethalThings-0.9.4
CTMods-KarmaForBeingAnnoying-1.1.0
Verity-TooManySuits-1.0.5
YELLOWGLASS-Yellowglass_Vibrant_Suits-1.4.1
Rune580-LethalCompany_InputUtils-0.6.1
HomelessGinger-MaskedEnemyOverhaul-3.1.1
FutureSavior-Hold_Scan_Button-1.1.1
Hamunii-JetpacksCarryBigItems-1.0.2
F4ilS4fe-MaskTheDead-1.0.5
Sakura-LandminesForAll-1.0.1
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
MegaPiggy-BuyableShotgun-1.0.4
MegaPiggy-BuyableShotgunShells-1.0.5
egeadam-MoreScreams-1.0.3
Fredolx-SignalTranslatorUpgrade-1.0.0
AllToasters-SpectateEnemies-2.2.1
Spiderbuttons-HandMirror-1.0.1
quackandcheese-MirrorDecor-1.3.1
Electric131-OuijaBoard-1.5.2
x753-Mimics-2.3.2
IntegrityChaos-Diversity-1.1.10
OE_Tweaks-Possessed_Masks-2.0.2
monkes_mods-JumpDelayPatch-1.0.1
taffyko-BetterSprayPaint-2.0.2
J3STER-J3STERsCosmeticsFixed-1.0.0
Mhz-MoreHead-1.2.5
TwinDimensionalProductions-CoilHeadStare-1.0.3
AgentRev-ShootableMouthDogs-1.0.1
EliteMasterEric-SlimeTamingFix-1.0.2
Bobbie-FixRPCLag-1.0.1
linkoid-DissonanceLagFix-1.0.0
CharlesE2-HostFixes-1.0.4
SZAKI-EnemyFix-1.0.0
Rocksnotch-CupboardFix-1.1.0
itsmeowdev-DoorFix-1.0.0
FishingsTeam-Lethal_Bug_Fixes-1.0.0
Zaggy1024-NutcrackerFixes-1.2.2
Ozone-Runtime_Netcode_Patcher-0.2.5
ControlCompany-ControlCompany-1.1.3
CTMods-ChatCommands-1.1.7
kuba6000-LC_Masked_Fix-0.0.2
KoderTeh-Boombox_Controller-1.1.9
MORT1F13R-MoreSuitColours-1.1.0
Hypick-Debugify-0.2.0
Zaggy1024-PathfindingLagFix-1.2.0
quackandcheese-ToggleMute-1.3.0
BlueAmulet-LogNeuter-1.0.3
Monkeytype-HideChat-1.0.0
GrimGrum-Lego_Yoda_DeathSFX-1.2.0
taffyko-NiceChat-1.2.4
HGG-JigglePhysicsPlugin-1.1.2
AinaVT-LethalConfig-1.3.4
Gemumoddo-LethalEmotesAPI-1.3.3
Gemumoddo-BadAssCompany-1.1.4
PotatoePet-AdvancedCompany-1.0.138
boxofbiscuits97-QuotaRollover-2.2.1
bizzlemip-NoPenalty-1.0.1

Yeh I know a lot of mods! I've also disabled mods so I've removed them off the list.

Modpack: 018d4ed1-49ae-7c7a-41f5-9fb3fb8a3413

**Comment by FluffyFishGames** [comment]
This problem should be fixed with 139.

**Comment by ToastedOven** [comment]
This was some weird 3-way incompatibility with LethalEmotesAPI, More_Emotes, and Advanced Company. I assume there is some code to fix More_Emotes not resetting bone positions when pulling out the portable terminal. LethalEmotesAPI has it's own code to reset bone positions when finished emoting but it seemed like it was firing in order of AC -> EmotesAPI, which caused issues, I changed my patch for the terminal opening to unlock the emote bones early, allowing AC to do it's stuff no problem.
