### ISSUE TITLE
[Incompatibility] Runtime Netcode Patcher

### ISSUE THREAD

**Issue by BellaRoka** [FluffyFishGames/AdvancedCompany#31]
Advanced Company v1.0.138 has an issue with [Runtime Netcode Patcher v0.2.5](https://thunderstore.io/c/lethal-company/p/Ozone/Runtime_Netcode_Patcher/), which causes the perk terminal to be invisible when opened, making perks impossible to buy/respec.

**Comment by FluffyFishGames** [comment]
Incomplete report.

Can't reproduce. Tested it while working on 139 due to MoreEmotes and everything worked flawlessly.

**Comment by BellaRoka** [comment]
Did some further testing, and identified the issue is more with BetterEmotes than with Runtime Netcode Patcher itself. The conflict occurs when Advanced Company, Runtime Netcode Patcher, _and_ [BetterEmotes](https://thunderstore.io/c/lethal-company/p/KlutzyBubbles/BetterEmotes/) are all used together. 

I mistakenly believed the issue to primarily be with the Runtime Netcode Patcher as BetterEmotes had worked just fine with Advanced Company, until the BetterEmotes 1.4.0 update integrated Runtime Netcode Patcher, and disabling the patcher while using BetterEmotes v1.4.0 caused the perk terminal to be visible again.

Per your last comment, I installed MoreEmotes v1.3.3 instead and found no issues with both it and Runtime Netcode Patcher alongside Advanced Company.

Likely an issue with how BetterEmotes v1.4.0 implements Runtime Netcode Patcher.

(Latest testing done with both v1.0.138 & v1.0.140 of Advanced Company, Runtime Netcode Patcher v0.2.5, BetterEmotes v1.3.4 & v1.4.0, and More Emotes v1.3.3.)

**Comment by FluffyFishGames** [comment]
No, the problem is that I only support MoreEmotes as of now.

**Comment by BellaRoka** [comment]
Ah my mistake, I hadn't realized. The compatibility list still shows BetterEmotes as compatible, you might want to update that. Sorry for the confusion, and thanks for your time!
