### ISSUE TITLE
Cant join to the game

### ISSUE THREAD

**Issue by Hrenovik** [FluffyFishGames/AdvancedCompany#32]
After entering the game as a host, my friend could not join even if he had the mod.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/157962113/d7aea524-1c35-4a20-a076-55f2a14049b5)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/157962113/05761c1c-9a84-4e26-a4b5-2d76c85ec819)

[Info   : Unity Log] Has beta?: {hasBeta}
[Info   : Unity Log] Has beta save data: True
[Info   :AdvancedCompany] Activating necessary player objects for next player to join.
[Info   :AdvancedCompany] Next player object with ID 1 activated.
[Warning: Unity Log] [Dissonance:Recording] (11:53:04.515) CapturePipelineManager: Detected a frame skip, forcing capture pipeline reset (Delta Time:0,1675655)
[Info   :More Ship Upgrades] [LGUStore] Loading SteamID: 76561198173395067
[Info   :More Ship Upgrades] [LGUStore] Successfully loaded save data for ID: 76561198173395067
[Info   :More Ship Upgrades] [UpgradeBus] Sale data empty, continuing...
[Info   :More Ship Upgrades] [LGUStore] Applying loaded upgrades...
[Info   : Unity Log] Player joined w steamId: 76561198068354367
[Info   : Unity Log] [HELMET_CAMERAS] Ship camera founded...
[Info   : Unity Log] [HELMET_CAMERAS] Monitors were changed...
[Info   : Unity Log] [HELMET_CAMERAS] Turning off vanilla internal ship camera
[Message:AdvancedCompany] OnClientDisconnect for 1
[Warning:AdvancedCompany] Wasn't able to remove client 1
[Info   : Unity Log] Disconnect callback called
[Info   : Unity Log] Is server: True; ishost: True; isConnectedClient: True
[Info   : Unity Log] Disconnect callback called in gamenetworkmanager; disconnecting clientId: 1
[Info   : Unity Log] A Player disconnected but they were not in clientplayerlist
[Info   : Unity Log] Player joined w steamId: 76561198068354367
[Message:AdvancedCompany] OnClientDisconnect for 2
[Warning:AdvancedCompany] Wasn't able to remove client 2
[Info   : Unity Log] Disconnect callback called
[Info   : Unity Log] Is server: True; ishost: True; isConnectedClient: True
[Info   : Unity Log] Disconnect callback called in gamenetworkmanager; disconnecting clientId: 2
[Info   : Unity Log] A Player disconnected but they were not in clientplayerlist

**Comment by rgmoon** [comment]
Please provide the mod list

**Comment by Hrenovik** [comment]
> Please provide the mod list

![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/157962113/94fdff76-9cbc-465c-87b9-956969685608)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/157962113/8cbe50c5-12ed-406e-9be8-4ef8d25c7db1)

**Comment by Hrenovik** [comment]
Problem was in lethallib
