### ISSUE TITLE
Deadline resets to vanilla value after quota reached.

### ISSUE THREAD

**Issue by MrWolfenstache** [FluffyFishGames/AdvancedCompany#34]
**Describe the bug**
Whenever I reach the deadline quota and sell of the items the custom value of 0 days for the deadline resets to the vanilla value of 3 days after the first quota.

**To Reproduce**
1. Set the deadline to a custom value 
2. Finish deadline
3. Start new deadline
4. Deadline resets into vanilla value of 3 days

                               Or

1. Set deadline 0
2. Kill yourself by fall damage
3. Let the game reset
4. Deadline resets into vanilla value of 3 days

**Screenshots**
AC setting.
![Screenshot (38)](https://github.com/FluffyFishGames/AdvancedCompany/assets/155269754/f90cbc5f-02ab-46a0-a587-62361f2af2ea)
![Screenshot (39)](https://github.com/FluffyFishGames/AdvancedCompany/assets/155269754/8f8a2993-c48e-472a-a6be-c24afdd0a059)
Before "I set it 0 so it would be faster to showcase"
![Screenshot (40)](https://github.com/FluffyFishGames/AdvancedCompany/assets/155269754/43fda4fd-5cfd-488c-b2c7-f7fea99d5e14)
After "You're Fired"
![Screenshot (41)](https://github.com/FluffyFishGames/AdvancedCompany/assets/155269754/a6d0bacb-9c66-4057-be49-4466c2d3f9c5)

**Expected behavior**
The deadline value to reset at 0 days after quota reached.

**Additional context**
At first I thought the cause was of other mods that use the deadline value but after deleting said mods the issue still persists.

**Edit**
It happens after the failing the quota too which resets the deadline to 3 days and also givers credits even though I have set it to 0 in AC menu.

**Add a list of all of your mods**

018d5118-612e-2014-ede8-5996ce9017eb

BepInEx-BepInExPack-5.4.2100
RugbugRedfern-Skinwalkers-4.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
x753-More_Suits-1.4.1
RickArg-Helmet_Cameras-2.1.5
x753-Mimics-2.3.2
Suskitech-AlwaysHearActiveWalkies-1.4.4
sunnobunno-YippeeMod-1.2.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
FlipMods-LetMeLookDown-1.0.1
EliteMasterEric-Coroner-1.5.3
FlipMods-TooManyEmotes-1.8.2
Verity-TooManySuits-1.0.5
AlexCodesGames-AdditionalContentFramework-1.0.3
Drakorle-MoreItems-1.0.2
Rune580-LethalCompany_InputUtils-0.6.1
notnotnotswipez-MoreCompany-1.7.6
itsmeowdev-DoorFix-1.0.0
TwinDimensionalProductions-CoilHeadStare-1.0.3
EladNLG-EladsHUD-1.2.1
MegaPiggy-BuyableShotgunShells-1.0.5
Hexnet111-SuitSaver-1.1.4
MegaPiggy-BuyableShotgun-1.0.4
FutureSavior-Hold_Scan_Button-1.1.1
Ozone-BepInUtils-1.2.1
Ozone-Glow_Steps-1.1.2
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
amnsoft-EmployeeAssignments-1.1.0
Monkeytype-HideChat-1.0.0
togglemybits-Strange_Objects-1.2.3
ohotdog-LootableMusicTapes-1.0.1
2018-LC_API-3.4.5
BLKNeko-HookGun-1.3.4
IntegrityChaos-Diversity-1.1.10
BunyaPineTree-ModelReplacementAPI-2.3.6
FoxGod-ThiccCompanyModelReplacement-2.0.1
BatTeam-LethalFashion-1.0.6
Owen3H-IntroTweaks-1.4.2
ASmolBoy-Intro_Company_Speech_Extended_Remix-1.0.0
Pinta-PintoBoy-1.0.4
Mellowdy-HandheldMap-1.0.0
Dwarggo-Fashion_Company-1.3.0
CyanBlob-Motion_Tracker-1.0.0
Silvercore-Permanent_Ladder-1.0.3
eXish-Batteries-1.0.4
BlueAmulet-LCBetterClock-1.0.3
KoderTeh-Boombox_Controller-1.1.9
CTNOriginals-CrossHair-1.0.5
ENZ-Lock_Doors_Mod-1.1.0
MegaPiggy-InsanityMeter-1.0.0
darmuh-ghostCodes-1.5.1
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
bigmcnugget-VanillaContentExpansion-0.1.8
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.5
HolographicWings-LethalExpansion-1.3.25
sfDesat-Orion-1.2.3
sfDesat-ExpansionAssets-1.0.0
sfDesat-Aquatis-1.1.0
Magic_Wesley-Infernis-1.5.2
LethalMoonTeam-Ether-1.6.2
FireNoobsta-Ducks_Moons-1.1.3
Magic_Wesley-Acidir-2.0.0
Magic_Wesley-Etern-1.3.4
Generic_GMD-Generic_Moons-3.1.1
AudioKnight-StarlancerMoons-0.3.1
AudioKnight-StarlancerMusic-1.1.0
AudioKnight-Starlancer-0.4.1
sfDesat-Celest-0.2.1
jockie-LethalExpansionCoreModules-1.3.5
Xaymar-Assal-1.2.1
Olemyth-Crypt-1.3.3
BudgetAirpods-InsanityRemastered-1.1.2
PotatoePet-AdvancedCompany-1.0.139
Jamil-Corporate_Restructure-1.0.6
EliteMasterEric-WackyCosmetics-2.0.0
NiaNation-AbsasCosmetics-1.2.3
HGG-JigglePhysicsPlugin-1.1.2
Mhz-MoreHead-1.2.5
bandaidroo-BandaidsMegaCosmetics-1.1.0
broiiler-inacraft_cosmetics_megapack-1.0.1
ZTK-ZTKCosmetics-2.0.0
Hexa-Hexas_Cosmetics-0.0.2
companyemployee-EquipmentCompany-1.3.0
Sluka-CosmeticMegapack-1.2.0
fonnymunkey-SimpleHats-1.0.0
Insomniax-InsomniaxCosmetics-1.2.0
Pooble-LCBetterSaves-1.7.3
HomelessGinger-MaskedEnemyOverhaul-3.1.1
kuba6000-LC_Masked_Fix-0.0.2
KoderTeh-Television_Controller-1.0.3
MonAmiral-PlayerDogModel-1.0.3
mrov-LethalRichPresence-0.5.7
IAmBatby-LethalLevelLoader-1.0.7
NomnomAB-RollingGiant-2.4.4
TheFluff-FairAI-1.3.2
malco-Lategame_Upgrades-3.1.0
Evaisa-LethalThings-0.9.4
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
LethalResonance-LETHALRESONANCE-2.2.8
aqua_dot-CompanyWardrobe-1.0.1
Smxrez-SmoreCosmetics-1.5.0
Major_And_Skiz-MoreInteriors-1.3.0
Alice-ScarletDevilMansion-1.1.7
HolographicWings-ChristmasVillage_Legacy-1.3.16
scoopy-Scoopys_Variety_Mod-0.6.5
RedCrowbar-BuffedPresents-0.0.5
malco-SellBodies-1.1.0
DrinkableWater-Brutal_Company_Minus-0.7.3
NotAtomicBomb-TerminalApi-1.5.1
loaforc-FacilityMeltdown-2.1.1
Spyci-CozyImprovements-1.2.2
Badham_Mods-SCPFoundationDungeon-2.2.0
Search for a setting

**Comment by FluffyFishGames** [comment]
Should be fixed with 141
