### ISSUE TITLE
Weird player model pose in cosmetics tab

### ISSUE THREAD

**Issue by LethalHotkeys** [FluffyFishGames/AdvancedCompany#37]
**Describe the bug**
The player model has a weird pose in the cosmetics tab.

**To Reproduce**
1. Go to AdvancedCompany Settings
2. Click on Cosmetics Tab
3. See error

**Expected behavior**
The player model should be dancing.

**Screenshots**
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/125814562/7adbf53e-9594-47b8-bb80-7f73d1133a97)

**Additional context**
This happens even when only advancedcompany is installed.

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14077084/Player.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.139

Profile Code:
018d5144-b574-c66d-f6d9-f4858912972a

**Comment by FluffyFishGames** [comment]
Will be fixed in 141
