### ISSUE TITLE
Multiplayer Inventory Slot

### ISSUE THREAD

**Issue by Rezay27** [FluffyFishGames/AdvancedCompany#38]
**Describe the bug**
Client side player have access to all slot without having the stat augment up (slot are not visible as intended but are still accessible for client only, the host work fine)

**To Reproduce**
Create a game , invite friend , friend scroll or us key to access slots and can just take 10 item if they want

**Expected behavior**
Client side player can't take more that what they have unlocked or be able to scroll on locked inventory slot

**Additional context**

**Logfiles**
in a .zip

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.140

[Logs.zip](https://github.com/FluffyFishGames/AdvancedCompany/files/14077456/Logs.zip)

**Comment by vermilionshadow-vk** [comment]
I also experienced this bug in my run, I was a non-host in my run as well too:
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14079167/Player.log)

I had it with the following mods:
Profile code: 018d532b-a5e6-c655-d3db-151191a3a8fb

BepInEx-BepInExPack-5.4.2100
NotAtomicBomb-TerminalApi-1.5.1
AlexCodesGames-AdditionalContentFramework-1.0.3
Rune580-LethalCompany_InputUtils-0.6.1
sfDesat-ExpansionAssets-1.0.0
jockie-LethalExpansionCore-1.3.15
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.0
IAmBatby-LethalLevelLoader-1.0.7
sunnobunno-YippeeMod-1.2.3
RugbugRedfern-Skinwalkers-4.0.1
Pooble-LCBetterSaves-1.7.3
Monkeytype-HideChat-1.0.0
BlueAmulet-NameFix-1.0.1
AlexCodesGames-AdditionalSuits-2.0.0
notnotnotswipez-MoreCompany-1.7.6
FlipMods-TooManyEmotes-1.8.3
FlipMods-LetMeLookDown-1.0.1
echoman-Uninvertible_Jetpack-0.0.1
Piggy-ShowCapacity-1.0.7
Suskitech-AlwaysHearActiveWalkies-1.4.4
AgeCo-AgeSignals-1.0.1
boring-CustomTranslatorCharLimit-1.0.2
ThePotato-scanForItemsFix-1.0.4
TheDeadSnake-Touchscreen-1.0.8
Zaggy1024-OpenBodyCams-1.0.20
Jamil-Corporate_Restructure-1.0.6
akechii-DiscountAlert-2.3.0
Dreamweave-CompanyBuildingEnhancements-2.6.0
LethalOrg-ProgressiveDeadline-2.0.0
Nozz-Lethal_Missions-1.1.6
Evaisa-LethalThings-0.9.4
Justice69-ImmersiveScraps-1.1.5
PotatoePet-AdvancedCompany-1.0.140
sfDesat-Aquatis-1.1.0
TeamBridget-Peaches_Castle-1.0.41
Boniato-Ganimedes-1.6.0
Ceelery-Kast-1.0.3

**Comment by Lerrycapetime** [comment]
Same problem, very easy to replicate.

**Comment by FluffyFishGames** [comment]
Will be fixed in next version.
