### ISSUE TITLE
Client not honoring host settings for disabled perks

### ISSUE THREAD

**Issue by Tyaeth** [FluffyFishGames/AdvancedCompany#4]
**Describe the bug**
When starting a server that disables some Advanced Company perks, the host is unable to see those perks (as expected) but clients are able to see and purchase the disabled perks. 

**To Reproduce**
1. Start up a new multiplayer session and disable some perks in the configuration.
2. Have someone join your game and check the perks in the portable terminal
3. The joining player should be able to purchase the perks that were marked as disabled in the configuration.

**Expected behavior**
Clients should not be able to see or purchase perks that were disabled in the host's configuration.

**Screenshots**
Host Screenshot:
![host_screenshot](https://github.com/FluffyFishGames/AdvancedCompany/assets/6688230/7cba25cf-7dd2-4b97-a4b6-9385d7ae4d0c)
Client Screenshot:
![client_screenshot](https://github.com/FluffyFishGames/AdvancedCompany/assets/6688230/0fb3d57e-93c8-4533-8931-584a5db58a9c)

**Additional context**
Logs were taken on a freshly made Thunderstore profile, so all configurations were generated fresh.

**Logfiles**
[Host_Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14031109/Host_Player.log)
[Client_Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14031112/Client_Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.131
Pooble-LCBetterSaves-1.7.3

**Comment by FluffyFishGames** [comment]
Will be fixed in the next version. Occured because of another bugfix which wasnt needed any longer.

**Comment by FluffyFishGames** [comment]
I consider this bug fixed :) Reopen the ticket if the problem persists.
