### ISSUE TITLE
Monitor Labels Incompatibility

### ISSUE THREAD

**Issue by CommanderSlav** [FluffyFishGames/AdvancedCompany#40]
Advanced Company 140

It seems that AC 139 / 140 when used with MonitorLabels v1.3.1 by DannyVD, completely "breaks" the inventory, more specifically, regardless of inventory size, it sets it to 10. 
I have tested this on a fresh profile with 0 modifications and only 2 mods. 
These mods worked fine along each other in 138. Not sure who is to blame. Monitorlabels has not changed since 138.

[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14077680/LogOutput.log)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/67171084/fbfb43fa-40e6-43cb-be9c-330d93677f3c)

**Comment by FluffyFishGames** [comment]
Its a missing null check in that mod.
