### ISSUE TITLE
Compability Report: Facility Meltdown custom apparatus value doesn't get affected by the multiplier.

### ISSUE THREAD

**Issue by XenoX6080** [FluffyFishGames/AdvancedCompany#44]
Please state the used AdvancedCompany version and the mod which is incompatible or compatible.

Just updated to 1.0.140 and tried to test the custom apparatus values, welp... doesn't work. No idea if it's not fully implemented or the custom prices are overriding the multiplied default value of the apparatus.

I've seen the discord, you said something about apparatus multiplied by 0.4. 

Value multiplier is set to 50%, so the value of the apparatus should be 80 * 0.5 * 0.4 so it should be 16. The modified value using Facility Meltdown is 240 so it should be 3 times as that which is 48.

Test 1
Advanced Company: Enabled
Facility Meltdown: Disabled
Result: 16

Test 2
Advanced Company Enabled
Facility Meltdown: Enabled (Override: false)
Result: 16

Test 3
Advanced Company Enabled
Facility Meltdown: Enabled (Override: true)
Result: 240

I know that making compatibility with every mod possible is getting irritating, I really do. If it's not possible to fix it maybe getting the apparatus value and weight setting to the scrap.json might be a good idea idk.

As for the modlist:
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
**PotatoePet-AdvancedCompany-1.0.140**
Evaisa-HookGenPatcher-0.0.5 << needed for FM to work
Evaisa-LethalLib-0.14.0 << needed for FM to work
NotAtomicBomb-TerminalApi-1.5.1 << needed for FM to work
**loaforc-FacilityMeltdown-2.1.1**

**Comment by FluffyFishGames** [comment]
Should be fixed in next version
