### ISSUE TITLE
Bugs with Clients not able to see custom enemies or certain items.

### ISSUE THREAD

**Issue by Lerrycapetime** [FluffyFishGames/AdvancedCompany#45]
Very simple bug, mods such as custom enemies, Skibidi Toilet, SCP-096, RollingGiant or LethalThings items are not visible for clients, ONLY host! They detect the player but won't hurt them. Not sure what causes it as for the item mod [CollectorsScrapTest](https://thunderstore.io/c/lethal-company/p/ByteBuddies/CollectorsScrapTest/) and [MinecraftScraps](https://thunderstore.io/c/lethal-company/p/rainbow137/MinecraftScraps/) works fine.

**Comment by AntonyMLG** [comment]
LethalLib New update problem i think. I fixed it by downgrading it to 0.13.2.

**Comment by Lerrycapetime** [comment]
Just checked the GitHub page for LethalLib, def a LethalLib problem and not this mod, thanks btw!
