### ISSUE TITLE
Per-moon Settings Display Incorrectly on First Generation

### ISSUE THREAD

**Issue by nyctodarkmatter** [FluffyFishGames/AdvancedCompany#5]
**Describe the bug**
Upon generating the configuration settings for moons for the first time by loading into the game, almost any setting that has a default value of 0 will instead display as "X 100", with the only exception being the price field. Any value in the Loot table or any of the three Enemies list fields appears to display this way, though there are occasionally exceptions for unknown reasons. This is fixed if the game is restarted, and appears to only be visual.

**To Reproduce**
1. Delete config files
2. Launch game with no config files and load into a fresh save
3. Leave game and view the "Moons" tab upon launching the save file again
4. See "X 100" in various checkboxes across the Moons settings.

**Expected behavior**
Expect to see a Rarity of 0 with an unmodified checkbox on various moon settings.

**Screenshots**
![image_2024-01-24_022749204](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/193c03e8-c7f4-40f5-9db5-87f5e31e5cbc)

**Additional context**
As stated, this appears to be entirely visual and is fixed upon a game restart. That said, for those like me who like to check all their settings in a quick manner, it is definitely a jarring visual bug.

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14034907/LogOutput.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.4.5
x753-More_Suits-1.4.1
x753-Mimics-2.3.2
tinyhoot-ShipLoot-1.0.0
RugbugRedfern-Skinwalkers-4.0.1
AlexCodesGames-AdditionalSuits-2.0.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
Rune580-LethalCompany_InputUtils-0.6.0
KoderTeh-Boombox_Controller-1.1.9
FlipMods-LetMeLookDown-1.0.1
EliteMasterEric-Coroner-1.5.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
Evaisa-LethalThings-0.9.4
NotAtomicBomb-TerminalApi-1.5.1
NotAtomicBomb-Terminal_Clock-1.0.5
BatTeam-LethalFashion-1.0.6
EliteMasterEric-SlimeTamingFix-1.0.2
Backrooms-Backrooms-0.1.3
TeamClark-SCP_Foundation_Suit-1.1.0
Electric131-OuijaBoard-1.5.2
CyanBlob-Motion_Tracker-1.0.0
CHILLAX-ChillaxSCRAPS-0.6.0
itsmeowdev-DoorFix-1.0.0
Pooble-LCBetterSaves-1.7.3
FlipMods-SkipToMultiplayerMenu-1.0.0
FlipMods-FasterItemDropship-1.2.1
Badham_Mods-SCPFoundationDungeon-2.1.0
Monkeytype-HideChat-1.0.0
Rattenbonkers-TVLoader-1.1.1
cubly-ColourfulFlashlights-2.2.0
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
Nephren-MineTurtle-1.1.0
HolographicWings-LethalExpansion-1.3.22
sfDesat-Orion-1.2.3
sfDesat-Aquatis-1.1.0
scoopy-Scoopys_Variety_Mod-0.6.5
Ceelery-Kast-1.0.3
IAmBatby-LethalLevelLoader-1.0.7
Zingar-SecretLabs-3.3.4
Zingar-Atlas_Abyss-1.1.5
Jordo-NeedyCats-1.1.1
ViViKo-ItemClippingFix-1.1.3
ThePotato-scanForItemsFix-1.0.4
ShaosilGaming-FlashlightFix-1.0.5
Piggy-ShowCapacity-1.0.7
malco-SellBodies-1.1.0
stormytuna-KindTeleporters-1.0.3
loaforc-FacilityMeltdown-2.0.2
BlockHead-PolaroidCamera-0.1.9
Nyxchrono-DoorBreach-1.1.0
PC-FireExitFlip-1.0.0
OrangeSoft-Unlimited_Sell_Mod-1.0.0
jockie-LethalExpansionCore-1.3.14
notnotnotswipez-MoreCompany-1.7.6
Mhz-MoreHead-1.2.5
bandaidroo-BandaidsMegaCosmetics-1.0.0
Hexa-Hexas_Cosmetics-0.0.2
Luigi-Nintendo_Hats-1.4.0
NiaNation-AbsasCosmetics-1.2.3
raydenoir-SCP173CoilheadSFX-1.3.1
quackandcheese-MirrorDecor-1.3.1
Clementinise-QuickTerminalRestart-1.0.3
Karster-Light_Switch_Scan_Node-1.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
AlexCodesGames-AdditionalContentFramework-1.0.3
Misofist-LCConductivityFix-0.0.1
AllToasters-SpectateEnemies-2.2.1
Zaggy1024-PathfindingLagFix-1.2.0
Speakers-IndieGameScrap-1.2.0
F4ilS4fe-MaskTheDead-1.0.5
AudioKnight-StarlancerMoons-0.3.0
sfDesat-ExpansionAssets-1.0.0
PrinceNailo-Family_Guy_Funny_Moments-1.2.0
FlipMods-ObjectVolumeController-1.0.4
FlipMods-TooManyEmotes-1.8.1
SillySquad-TakeThatMaskOff-1.3.0
Magic_Wesley-Infernis-1.5.1
Magic_Wesley-Etern-1.3.3
Magic_Wesley-Acidir-2.0.0
sfDesat-Celest-0.2.1
Major_And_Skiz-MoreInteriors-1.2.1
RedHuskyStudios-USC_Vortex-1.0.5
HomelessGinger-MaskedEnemyOverhaul-3.1.1
Alice-ScarletDevilMansion-1.1.3
HGG-JigglePhysicsPlugin-1.1.2
darmuh-ghostCodes-1.5.1
willis81808-LethalSettings-1.3.0
Nikki-NikkisCosmeticKingdom-1.0.0
PotatoePet-AdvancedCompany-1.0.131

Profile code: 018d3a60-95b3-a393-0030-e561ead0f731
(Delete configs for AdvancedCompany before testing if the profile code is used!)

**Comment by FluffyFishGames** [comment]
This only happened with the unsaved default config. Will be fixed in next release.

**Comment by FluffyFishGames** [comment]
I consider this bug fixed :) Reopen the ticket if the problem persists.
