### ISSUE TITLE
Certain enemies not spawning when customizing moon configs

### ISSUE THREAD

**Issue by Xiernix** [FluffyFishGames/AdvancedCompany#50]
**Describe the bug**
Changing spawn weights for enemies on moons who's default spawn chance is 0 doesn't spawn them and throws out an error when the game tries to spawn them in while still adding the enemy's power to the moons max power count. (e.g. trying to spawn coil-heads on Experimentation or the ghost girl on Offense when by default their spawn weight is 0.) This will eventually lead to the moon hitting it's spawn cap without anything actually spawning in.

**To Reproduce**

1. Go to Moons in the config that pops up before starting a game.
2. Click on Experimentation.
3. Scroll down to the Inside enemies list Section.
4. Check the box for Spring and change the value to 9999.
5. Start the game and land on Experimentation.
6. The game will try to spawn in coil-heads but nothing will spawn in and the indoor power will raise by 1.

**Expected behavior**
The enemy in question should spawn in a vent somewhere in the facility. If an enemy isn't allowed to be spawned in for whatever reason it would be preferable if it's settings were ignored instead of trying to spawn it and taking away both a spawn chance of another enemy and adding to the total power.

**Additional context**
This also applies to trying to give a spawn weight to the outside enemies that populate the inside list in the configs. While I don't expect things like giants and eyeless dogs to actually spawn inside if someone where to configure them to try and spawn they would run into the same problem.

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14092317/Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.143

**Comment by Lerrycapetime** [comment]
I think this might also be a bug with setting up custom enemy spawns on the map Infernis.

**Comment by FluffyFishGames** [comment]
Has been fixed in 146 or so. Try 147
