### ISSUE TITLE
Custom Deadline Resets after 1st Quota

### ISSUE THREAD

**Issue by Rukia1727** [FluffyFishGames/AdvancedCompany#57]
**Describe the bug**
We set our custom deadline to 5 days. After getting to 5 days the quota reset back to 3 days and never went back. I tried to set it in the profile when loading the save but it doesn't revert back to the custom date I set. 

**To Reproduce**
1. Set deadline to 1 day
2. Get scrap, go to company
3. Complete Quota, get new quota and deadline is back to 3 days

**Expected behavior**
The deadline should stay at 5 days (what we set it to) no matter what and shouldn't reset. It should always be 5 days

**Additional context**
It happens with both my friend or me hosting the game

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14102088/Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.7.6
RugbugRedfern-Skinwalkers-4.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
anormaltwig-LateCompany-1.0.10
x753-Mimics-2.3.2
RickArg-Helmet_Cameras-2.1.5
sunnobunno-YippeeMod-1.2.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
Backrooms-Backrooms-0.1.3
EliteMasterEric-WackyCosmetics-2.0.0
TwinDimensionalProductions-CoilHeadStare-1.0.5
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
Rattenbonkers-TVLoader-1.1.1
KoderTeh-Boombox_Controller-1.1.9
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
TheFluff-FairAI-1.3.2
cuminas-FreeBirdJesterMod-1.0.3
sunnobunno-LandMineFartReverb-1.0.3
BunyaPineTree-ModelReplacementAPI-2.3.6
x753-More_Suits-1.4.1
FoxGod-ThiccCompanyModelReplacement-2.0.1
AinaVT-LethalConfig-1.3.4
readthisifbad-SnatchinBracken-1.3.5
PopleZoo-BetterItemScan-3.0.1
Panton-Racist_Yippie_Hoarding_Bugs-1.0.11
thisMicki-BrackenFavRoom-0.1.9
FlipMods-TooManyEmotes-1.8.5
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.143
MegaPiggy-BuyableShotgunShells-1.0.5
MegaPiggy-BuyableShotgun-1.0.4
axd1x8a-LCAmmoCheck-1.1.1
malco-Lategame_Upgrades-3.1.1
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.7
PotatoCoders-MinimumQuotaFinder-1.0.1
HomelessGinger-MaskedEnemyOverhaul-3.1.1

**Comment by FluffyFishGames** [comment]
Duplicate #56
