### ISSUE TITLE
(v1.0.145) Advanced Company equipment Pricing bug

### ISSUE THREAD

**Issue by Strazyplus** [FluffyFishGames/AdvancedCompany#59]
**Describe the bug**
Several items prices get changed to zero when you start hosting a server. 

**To Reproduce**
1. hosting a server causes items.json various prices to be modified to zero

**Related bug reports**
Other bug reports the same behavior:
https://github.com/FluffyFishGames/AdvancedCompany/issues/58 https://github.com/FluffyFishGames/AdvancedCompany/issues/60

**Expected behavior**
Items to not be set as free. However once game starts items that had a price assigned to them get set to zero. forces zero value to certain items value.

**Screenshots**
Before starting server
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/6706750/a10ec717-ae15-409e-9d32-98f1f9344547)
in game prices.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/6706750/1769f9fa-4733-4b41-bc79-187b8bd6230c)
I exit to main menu and start server again.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/6706750/0d1967a8-5901-4342-88fc-986217dbcac5)

**Logfiles**
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14104636/Player.log)

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
Tyzeron-Minimap-1.0.5
sunnobunno-YippeeMod-1.2.3
xCeezy-LethalEscape-0.8.5
RugbugRedfern-Skinwalkers-4.0.1
TheFluff-FairAI-1.3.2
NiceHairs-NuclearLib-1.0.4
NiceHairs-Symbiosis-1.0.5
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
Evaisa-LethalThings-0.9.4
AinaVT-LethalConfig-1.3.4
Ozone-Runtime_Netcode_Patcher-0.2.5
readthisifbad-SnatchinBracken-1.3.5
HomelessGinger-MaskedEnemyOverhaul-3.1.1
kuba6000-LC_Masked_Fix-0.0.2
HolographicWings-LethalExpansion-1.3.25
RickArg-Helmet_Cameras-2.1.5
tinyhoot-ShipLoot-1.0.0
Rune580-LethalCompany_InputUtils-0.6.1
AllToasters-SpectateEnemies-2.2.1
Suskitech-AlwaysHearActiveWalkies-1.4.4
EliteMasterEric-Coroner-1.5.3
PopleZoo-BetterItemScan-3.0.1
Coomfy-CoomfyDungeon-1.0.12
egeadam-MoreScreams-1.0.3
IAmBatby-LethalLevelLoader-1.0.7
PocketWatchers-PocketWatcher-2.0.1
Renegades-WalkieUse-1.5.0
Sligili-More_Emotes-1.3.3
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.7
TwinDimensionalProductions-CoilHeadStare-1.0.5
Drakorle-MoreItems-1.0.2
Major_And_Skiz-MoreInteriors-1.3.0
linkoid-DissonanceLagFix-1.0.0
ScottyFoxArt-CompanyIssuedProtogen-1.0.0
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
PotatoePet-AdvancedCompany-1.0.144
2018-LC_API-3.4.5

018d5c52-29a9-475a-0267-f59014f523f3

**Comment by Strazyplus** [comment]
Everyone is suffering this problem so far we spotted three different bug reports.

https://github.com/FluffyFishGames/AdvancedCompany/issues/58 https://github.com/FluffyFishGames/AdvancedCompany/issues/59 https://github.com/FluffyFishGames/AdvancedCompany/issues/60

**Comment by Strazyplus** [comment]
This problem persists on v1.0.145 from v1.0.144

**Comment by Strazyplus** [comment]
To seek a temp bypass we downgraded to 143 and problem did no persist.

**Comment by FluffyFishGames** [comment]
Duplicate #58
