### ISSUE TITLE
Items from ChillaxSCRAPS log Incorrect Weight Values

### ISSUE THREAD

**Issue by nyctodarkmatter** [FluffyFishGames/AdvancedCompany#6]
**Describe the bug**
Items from ChillaxSCRAPS show an incorrect weight value in the Items config settings that does not correlate to their typical in-game weight. Does not appear to affect "Freddy Fast Bear?" and "Moai".

**To Reproduce**
1. Generate a fresh config by entering and leaving the game
2. Open up the Items tab in your Default preset
3. Check the entries for items from ChillaxSCRAPS (Boink, Cup Noodle, Death Note, Eevee Plush, Froggy Chair, Nokia 3310, Uno Reverse Card)
4. See negative weight value.

**Expected behavior**
Items would have a weight value of 0 or a reasonable, non-negative weight value.

**Screenshots**
![image_2024-01-24_024259011](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/413f44e1-3928-4949-b8e9-a0b6b19650e6)
![image_2024-01-24_024316219](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/9adf62b3-eef4-426c-a5d9-b33469aa09ba)
![image_2024-01-24_024331924](https://github.com/FluffyFishGames/AdvancedCompany/assets/55568272/d282bab3-be22-45b6-b568-5a15e7760a5c)
(Other items are similar.)

**Additional context**
There is a possibility that these weight values are correct, and in-game an item's weight simply cannot go below 0, as I can't say I've ever noticed any of these items from ChillaxSCRAPS reduce my weight, but I also can't say I've paid a special amount of attention to them adding weight to the player, either (unlike notably heavy objects from other mods). I currently can't test further as I don't have the tools available to me and won't be able to test for quite a bit due to moving more than halfway across the USA.

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14035037/LogOutput.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
2018-LC_API-3.4.5
x753-More_Suits-1.4.1
x753-Mimics-2.3.2
tinyhoot-ShipLoot-1.0.0
RugbugRedfern-Skinwalkers-4.0.1
AlexCodesGames-AdditionalSuits-2.0.0
Suskitech-AlwaysHearActiveWalkies-1.4.4
Rune580-LethalCompany_InputUtils-0.6.0
KoderTeh-Boombox_Controller-1.1.9
FlipMods-LetMeLookDown-1.0.1
EliteMasterEric-Coroner-1.5.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
Evaisa-LethalThings-0.9.4
NotAtomicBomb-TerminalApi-1.5.1
NotAtomicBomb-Terminal_Clock-1.0.5
BatTeam-LethalFashion-1.0.6
EliteMasterEric-SlimeTamingFix-1.0.2
Backrooms-Backrooms-0.1.3
TeamClark-SCP_Foundation_Suit-1.1.0
Electric131-OuijaBoard-1.5.2
CyanBlob-Motion_Tracker-1.0.0
CHILLAX-ChillaxSCRAPS-0.6.0
itsmeowdev-DoorFix-1.0.0
Pooble-LCBetterSaves-1.7.3
FlipMods-SkipToMultiplayerMenu-1.0.0
FlipMods-FasterItemDropship-1.2.1
Badham_Mods-SCPFoundationDungeon-2.1.0
Monkeytype-HideChat-1.0.0
Rattenbonkers-TVLoader-1.1.1
cubly-ColourfulFlashlights-2.2.0
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
Nephren-MineTurtle-1.1.0
HolographicWings-LethalExpansion-1.3.22
sfDesat-Orion-1.2.3
sfDesat-Aquatis-1.1.0
scoopy-Scoopys_Variety_Mod-0.6.5
Ceelery-Kast-1.0.3
IAmBatby-LethalLevelLoader-1.0.7
Zingar-SecretLabs-3.3.4
Zingar-Atlas_Abyss-1.1.5
Jordo-NeedyCats-1.1.1
ViViKo-ItemClippingFix-1.1.3
ThePotato-scanForItemsFix-1.0.4
ShaosilGaming-FlashlightFix-1.0.5
Piggy-ShowCapacity-1.0.7
malco-SellBodies-1.1.0
stormytuna-KindTeleporters-1.0.3
loaforc-FacilityMeltdown-2.0.2
BlockHead-PolaroidCamera-0.1.9
Nyxchrono-DoorBreach-1.1.0
PC-FireExitFlip-1.0.0
OrangeSoft-Unlimited_Sell_Mod-1.0.0
jockie-LethalExpansionCore-1.3.14
notnotnotswipez-MoreCompany-1.7.6
Mhz-MoreHead-1.2.5
bandaidroo-BandaidsMegaCosmetics-1.0.0
Hexa-Hexas_Cosmetics-0.0.2
Luigi-Nintendo_Hats-1.4.0
NiaNation-AbsasCosmetics-1.2.3
raydenoir-SCP173CoilheadSFX-1.3.1
quackandcheese-MirrorDecor-1.3.1
Clementinise-QuickTerminalRestart-1.0.3
Karster-Light_Switch_Scan_Node-1.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
AlexCodesGames-AdditionalContentFramework-1.0.3
Misofist-LCConductivityFix-0.0.1
AllToasters-SpectateEnemies-2.2.1
Zaggy1024-PathfindingLagFix-1.2.0
Speakers-IndieGameScrap-1.2.0
F4ilS4fe-MaskTheDead-1.0.5
AudioKnight-StarlancerMoons-0.3.0
sfDesat-ExpansionAssets-1.0.0
PrinceNailo-Family_Guy_Funny_Moments-1.2.0
FlipMods-ObjectVolumeController-1.0.4
FlipMods-TooManyEmotes-1.8.1
SillySquad-TakeThatMaskOff-1.3.0
Magic_Wesley-Infernis-1.5.1
Magic_Wesley-Etern-1.3.3
Magic_Wesley-Acidir-2.0.0
sfDesat-Celest-0.2.1
Major_And_Skiz-MoreInteriors-1.2.1
RedHuskyStudios-USC_Vortex-1.0.5
HomelessGinger-MaskedEnemyOverhaul-3.1.1
Alice-ScarletDevilMansion-1.1.3
HGG-JigglePhysicsPlugin-1.1.2
darmuh-ghostCodes-1.5.1
willis81808-LethalSettings-1.3.0
Nikki-NikkisCosmeticKingdom-1.0.0
PotatoePet-AdvancedCompany-1.0.131

Profile code: 018d3a60-95b3-a393-0030-e561ead0f731

**Comment by FluffyFishGames** [comment]
Working as intended. The values they gave for weight are totally wrong.
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/12402209/36314473-d191-4b72-a68d-d368d03551e7)
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/12402209/87de1083-fb5b-443f-97a0-90f85e5b8502)

Weight only allows values greater or equal to 1.
