### ISSUE TITLE
Portable Terminal Animations

### ISSUE THREAD

**Issue by Autumnis** [FluffyFishGames/AdvancedCompany#64]
Sometimes when others are using the portable terminal it seems that it can sometimes disappear from their hands.

It usually happens when someone else has the portable terminal open, and then I equip and unequip it.

What is expected to happen is the portable terminal to obviously well, not disappear from someone's hands.

I currently do not have screenshots.

I do not have any mods that mess with animations.

**Comment by Hardeh** [comment]
Had same thing today, terminal sometimes forget to appear and players look like touching empty air while using terminal

**Comment by FluffyFishGames** [comment]
Fixed in 148
