### ISSUE TITLE
Weird Portable Terminal interactions in a few scenarios

### ISSUE THREAD

**Issue by ToastedOven** [FluffyFishGames/AdvancedCompany#65]
**Describe the bug**
Yeah so in a few strangely specific scenarios, it seems like whatever patches you have to fix (or something like that) the portable terminal animation don't work properly.

**To Reproduce**
Download either 
018d5e13-d0ca-fbef-147c-99a1b6ccd210 (small and concise, breaks when LethalExpansion is enabled)
018d5e1f-8f05-d182-10d7-5d654faba7b4 (more of a full pack, breaks in the same way, but only when broiiler's emotes is enabled)

Attempt to open the terminal

In both of these, it breaks with the specified mod turned on, or MoreEmotes. Disabling the specified mod or MoreEmotes fixes the issue

**Expected behavior**
Portable Terminal should pull up properly

**Screenshots**
![Lethal_Company_GJU5VBEhGN](https://github.com/FluffyFishGames/AdvancedCompany/assets/49164897/c4d2364d-3dc8-4833-9858-4cc54b2c9ec6)

**Additional context**
from my perspective, it seems like in both of these cases. Whatever patch you have for MoreEmotes is failing to apply correctly, but at the same time I do not see any errors in the log indicating such.

**Logfiles**
Both of these logs are from the first modpack code listed above
[BepinExLog LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14107895/LogOutput.log)
[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14107927/Player.log)

**Add a list of all of your mods**

For code 1:
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.145
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
HolographicWings-LethalExpansion-1.3.25

For code 2: (note that not all of these are enabled)
BepInEx-BepInExPack-5.4.2100
broiiler-broiilers_silly_emotes-1.1.7
2018-LC_API-3.4.5 --------- DISABLED
RugbugRedfern-Skinwalkers-4.0.1
FlipMods-TooManyEmotes-1.8.6
Magic_Wesley-Acidir-2.0.0
Magic_Wesley-Etern-1.3.4
Keyble-Nerd_Scraps-1.1.4
Rune580-LethalCompany_InputUtils-0.6.1
Evaisa-LethalLib-0.14.2
Insomniax-InsomniaxCosmetics-1.2.0
FlipMods-ReservedItemSlotCore-1.8.17 --------- DISABLED
FlipMods-ReservedFlashlightSlot-1.6.3 --------- DISABLED
HomelessGinger-MaskedEnemyOverhaul-3.1.1
HolographicWings-LethalExpansion-1.3.25
FlipMods-ReservedWalkieSlot-1.6.2 --------- DISABLED
EliteMasterEric-WackyCosmetics-2.0.0
Caigan-Tokucade_Scrap-1.5.0
IAmBatby-LethalLevelLoader-1.0.7
Sligili-More_Emotes-1.3.3
Evaisa-LethalThings-0.9.4
jockie-LethalExpansionCore-1.3.15
sunnobunno-BonkHitSFX-1.0.5
Mhz-MoreHead-1.2.5
Pooble-LCBetterSaves-1.7.3
Zingar-Atlas_Abyss-1.1.6
Taker-CannabisCompany-1.0.3
ViViKo-ItemClippingFix-1.1.3
Jamil-Corporate_Restructure-1.0.6
x753-Mimics-2.3.2
notnotnotswipez-MoreCompany-1.7.6
Hexnet111-SuitSaver-1.1.4
Zingar-SecretLabs-3.3.4
anormaltwig-LateCompany-1.0.10 --------- DISABLED
quackandcheese-MirrorDecor-1.3.1
PC-FireExitFlip-1.0.0
Nuts-LethalPlushies-1.7.1
Ozone-Runtime_Netcode_Patcher-0.2.5
FlipMods-FasterItemDropship-1.2.1
Azim-LethalPresents-1.0.4
Jordo-NeedyCats-1.1.1
Verity-TooManySuits-1.0.5
xboxcontroller-LCThirdPerson-1.0.4 --------- DISABLED
BACONGUDEN-VileValuables-1.0.2
akechii-DiscountAlert-2.3.0
EliteMasterEric-Coroner-1.5.3
FowD8-A_Few_More_Suits-1.5.1
Blorb-WeatherMultipliers-1.1.0 --------- DISABLED
pineapple3333-Scavenger_Plushie-1.0.3 --------- DISABLED
FlipMods-BetterStamina-1.3.2
llpaull-MineMineMineMod-1.1.0
ChooMcoo-MoreAdditionalSuits-1.0.2
Sligili-HDLethalCompany-1.5.6
OnePeak-Low_Budget_One_Piece_suits-0.5.1
PuffyMods-Kick_Me-1.1.0
ViViKo-AllTheScrap-1.0.1 --------- DISABLED
PuffyMods-Dunce_Cap-1.1.0
quackandcheese-ToggleMute-1.3.0
x753-More_Suits-1.4.1
RickArg-Helmet_Cameras-2.1.5
matsuura-HealthMetrics-1.0.2
Sv_Matt-HideModList-1.0.1
Midge-PushCompany-1.2.0
Monkeytype-HideChat-1.0.0
FlipMods-MoreBlood-1.0.2
FlipMods-SkipToMultiplayerMenu-1.0.0 --------- DISABLED
Evaisa-HookGenPatcher-0.0.5
FlipMods-LetMeLookDown-1.0.1
tinyhoot-ShipLoot-1.0.0
Insomniax-JaximuuhhsCaliicorppaModPack-1.4.2 --------- DISABLED
AinaVT-LethalConfig-1.3.4
Gemumoddo-BadAssCompany-1.1.4
Gemumoddo-LethalEmotesAPI-1.4.0
Sir_BananaCat-ToothlessDanceEmote-1.0.4
HGG-JigglePhysicsPlugin-1.1.2
mertvybasein-NekiyManEmotes-1.1.1
AnythingGoesGit-MoreDeathNotes-1.4.0 --------- DISABLED
willis81808-LethalSettings-1.3.0
Norman-Lightsabers-1.1.2
bizzlemip-BiggerLobby-2.6.0 --------- DISABLED
PotatoePet-AdvancedCompany-1.0.145
CHILLAX-ChillaxSCRAPS-0.6.0
NutNutty-SellTracker-1.2.1
mfwmt-SanrioSuits-1.3.1
CTMods-KarmaForBeingAnnoying-1.1.0

**Comment by ToastedOven** [comment]
Just updating this, was doing a bit more testing and with the same mod list from the tiny profile, if UnityExplorer is added, everything works as intended. https://youtu.be/tCiTXNelcL4 (youtube since it's too big of a file to upload to github)

**Comment by FluffyFishGames** [comment]
Should be fixed in 1.0.147. I will close this but we can reopen it if it persists.

**Comment by FluffyFishGames** [comment]
Reopen for now as I got a report this still happens.

**Comment by FluffyFishGames** [comment]
OK after reevaluation it seems to be fixed :D
