### ISSUE TITLE
0 on mod items

### ISSUE THREAD

**Issue by vgomasjaya** [FluffyFishGames/AdvancedCompany#66]
0 on mod items

**Comment by galdi0222** [comment]
If you mean the price of the items then you can easily fix it in the window that appears when you host a game

**Comment by Maartonius** [comment]
> If you mean the price of the items then you can easily fix it in the window that appears when you host a game

Getting the same issue, trying to default/fix the prices will just keep putting it at $0

**Comment by FluffyFishGames** [comment]
Duplicate #58
