### ISSUE TITLE
Portable terminal is invisible to all players in the sessions

### ISSUE THREAD

**Issue by galdi0222** [FluffyFishGames/AdvancedCompany#67]
**Describe the bug**
After pressing X (the button assigned to the portable terminal) the animation of opening the terminal is present but the terminal itself is invisible. You can still type in commands and hear sounds from the terminal but it is totally invisible to all players in the lobby.

**To Reproduce**
Press the button assigned to the terminal

**Expected behavior**
I expected to see the terminal 

**Screenshots**
(https://github.com/FluffyFishGames/AdvancedCompany/assets/158285077/a8995083-6b7e-4010-b809-fc41dc4a45ff) I dont have another player with me right now so i can't show it from another perspective :( 

**Additional context**

**Logfiles**

[Player.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14111276/Player.log)

**Add a list of all of your mods**

BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.1
PotatoePet-AdvancedCompany-1.0.145
RickArg-Helmet_Cameras-2.1.5
AlexCodesGames-AdditionalContentFramework-1.0.3
AlexCodesGames-AdditionalSuits-2.0.0
Sligili-HDLethalCompany-1.5.6
x753-Mimics-2.3.2
tinyhoot-ShipLoot-1.0.0
HomelessGinger-MaskedEnemyOverhaul-3.1.1
RugbugRedfern-Skinwalkers-4.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
KlutzyBubbles-BetterEmotes-1.4.2
AinaVT-LethalConfig-1.3.4
funfoxrr-ShowLootOnPlanet-1.0.5
jockie-LethalExpansionCore-1.3.15
Justice69-ImmersiveScraps-1.1.7
Muldjord-MuldjordCosmetics-1.0.0
ThePotato-scanForItemsFix-1.0.4
matsuura-HealthMetrics-1.0.2

**Comment by Hardeh** [comment]
Maybe conflict with BetterEmotes?

**Comment by galdi0222** [comment]
yep, for some reason this is the only mod i did not check
