### ISSUE TITLE
4-way mod incompatibility causing LLL moons to not load

### ISSUE THREAD

**Issue by anon-cfg** [FluffyFishGames/AdvancedCompany#68]
**AdvancedCompany v1.0.145**

Full mod list:
BepInEx-BepInExPack-5.4.2100
AinaVT-LethalConfig-1.3.4
Rune580-LethalCompany_InputUtils-0.6.1
Gemumoddo-LethalEmotesAPI-1.4.0
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
IAmBatby-LethalLevelLoader-1.0.7
-----Dependencies above^-----
AudioKnight-**StarlancerMoons**-0.3.1
PotatoePet-**AdvancedCompany**-**1.0.145**
jockie-**LethalExpansionCore**-1.3.15
broiiler-**broiilers_silly_emotes**-1.1.7

**r2modman Profile code**: 018d6061-479c-d1b1-60c2-d81cfdf58c95

When using these 4 mods together, the LLL moon, in this example, Starlancer's Auralis moon, (and all other LLL moons), does not appear in terminal and can't be travelled to, it seems to not be present in the game at all.

This issue only appears with all 4 mods installed together.
Config files are all default / deleted before testing

There are 4 independent ways that I found to solve the issue and make the moon work.

1. Only disable LethalExpansionCore
2. Only disable Broiilers silly emotes
3. Only disable Advanced Company
4. Downgrade AdvancedCompany to **v1.0.138** (The only way I could get all 4 mods to work together)

Attached are 5 log files, 1 of the issue, and 4 of the 4 solutions that fix the issue.

[Doesn't work - All mods enabled.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14114587/Doesn.t.work.-.All.mods.enabled.log)
[Works - All mods enabled AC v1.0.138.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14114590/Works.-.All.mods.enabled.AC.v1.0.138.log)
[Works - Just AC disabled.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14114595/Works.-.Just.AC.disabled.log)
[Works - Just LEC disabled.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14114597/Works.-.Just.LEC.disabled.log)
[Works -  Just BSE disabled.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14114598/Works.-.Just.BSE.disabled.log)

**Comment by ToastedOven** [comment]
Hey just jumping in, I was doing some testing on [the issue I created ](https://github.com/FluffyFishGames/AdvancedCompany/issues/65) I found that installing UnityExplorer fixed my problem, and testing with your profile it also fixes it. I can't say why and it seems really arbitrary, so you might be able to install other mods which fix the issue as well. But just throwing that out there if you need a temporary  workaround while the underlying issue gets fixed

**Comment by FluffyFishGames** [comment]
Should be fixed in 1.0.147. I will close this but we can reopen it if it persists.
