### ISSUE TITLE
Mask Cosmetic Reset After Death

### ISSUE THREAD

**Issue by Aeniema** [FluffyFishGames/AdvancedCompany#69]
**Describe the bug**
Mask Cosmetic disappeared after death.

**To Reproduce**
1. Die.
2. Respawn.

**Expected behavior**
Respawn with cosmetic.

**Screenshots**
N/A

**Additional context**
I think the helmet model piece from AC might be cause? Probs wrong as you can attach multiple cosmetics anyway. Unless something to do with Masked Enemy Support? The debug still says the cosmetic is worn though when visually it's gone from both client and host.

**Logfiles**
N/A - No errors/info produced. No Event of it. If you still want I will drop them in. 

**Add a list of all of your mods**
BepInEx-BepInExPack-5.4.2100
LethalCompany_InputUtils v0.6.1
PotatoePet-AdvancedCompany-1.0.145
Muldjord-MuldjordCosmetics-1.0.0
bandaidroo-BandaidsMegaCosmetics-1.1.0
PupVR-Pups_Cute_Cosmetics-1.1.5
Insomniax-InsomniaxCosmetics-1.2.0
AinaVT-LethalConfig-1.3.4

**Comment by Hardeh** [comment]
I'm not sure it's mask only, because today all my friends cosmetics disappeared after he died and reappeared after he applied it in settings once more.

**Comment by FluffyFishGames** [comment]
Will be fixed in 148
