### ISSUE TITLE
AdvancedCompany & MoreHead by Mhz

### ISSUE THREAD

**Issue by Daehlion** [FluffyFishGames/AdvancedCompany#72]
Hi,

[MoreHead](https://thunderstore.io/c/lethal-company/p/Mhz/MoreHead/) is a MoreCompany cosmetics mod by Mhz that a bunch of my friends and I use. I tried pairing it with AdvancedCompany, but its cosmetics don't appear in-game in AC's cosmetics tab. My best guess is there hasn't been any compatibility implemented between the two, so AC doesn't recognize it as another MoreCompany cosmetics mod.

(This is irrelevant to the compatibility report, but I gotta say I love Advancedcompany. I've had such an incredibly smooth experience playing with it on my mod list with friends, and all the bugs I've run into you already dealt with. I'm looking forward to whatever you implement next!)

**Comment by FluffyFishGames** [comment]
Yea, the mod is basically written only for MoreCompany by design. Nothing I can do here. I will add it to the incompability list.

And thanks for the great feedback! :)
