### ISSUE TITLE
Advanced Comapany store shows wrong price if an item is on discount

### ISSUE THREAD

**Issue by toxyy** [FluffyFishGames/AdvancedCompany#73]
**Describe the bug**
Advanced Comapany store shows wrong price if an item is on discount

**To Reproduce**
1. have item be on discount
2. press x
3. compare price with store price

**Expected behavior**
That the price account the discount

**Screenshots**
![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/29783193/b0235f78-c465-40a4-b0dd-5d94f412dd83)

**Additional context**

**Logfiles**
https://gist.github.com/toxyy/dc94a39da7d4eb8aff9941bec0dd5349

Please note: These logs will get overwritten everytime you start the game. So please get your logs right when the issue occured.

**Add a list of all of your mods**

![image](https://github.com/FluffyFishGames/AdvancedCompany/assets/29783193/723b48ad-b8f8-441c-8885-8ab7ea2e17c3)

**Comment by FluffyFishGames** [comment]
Will be fixed in 148
