### ISSUE TITLE
Excessively expensive scrap

### ISSUE THREAD

**Issue by Swrds7** [FluffyFishGames/AdvancedCompany#8]
**Describe the bug**
Scrap price is sometimes excessively high. It's very inconsistent and happens on random days/maps. We've had this happen on Titan, March and Experimentation. Items can have a value of anything between 1 and 2147483647. The price sometimes changes when picked up and dropped with no clear pattern.

**To Reproduce**
Happens randomly with no consistent pattern.

**Screenshots**
https://imgur.com/a/v6CNj1q

**Logfiles**
N/A

**Add a list of all of your mods**
018d3d2c-2035-76b4-79b7-a745e786701c

BepInEx-BepInExPack-5.4.2100
AinaVT-LethalConfig-1.3.4
Rune580-LethalCompany_InputUtils-0.6.0
PotatoePet-AdvancedCompany-1.0.135
2018-LC_API-3.4.5
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.13.2
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
AbyssalCompanyTeam-AbyssalAudio-1.3.1
togglemybits-Strange_Objects-1.2.3
299792458-MoreMoneyStart-2.1.0
RugbugRedfern-Skinwalkers-4.0.1
BudgetAirpods-InsanityRemastered-1.1.1
darmuh-ghostCodes-1.5.1
MegaPiggy-BuyableShotgunShells-1.0.4
Drakorle-MoreItems-1.0.2
Owen3H-IntroTweaks-1.4.2
sunnobunno-YippeeMod-1.2.3
x753-Mimics-2.3.2
Pooble-LCBetterSaves-1.7.3
PostMortem-BetterLightning-1.0.3
TheFluff-FairAI-1.3.1
EladNLG-EladsHUD-1.2.1
HomelessGinger-MaskedEnemyOverhaul-3.1.1
taffyko-NiceChat-1.2.4
PopleZoo-BetterItemScan-3.0.1
kRYstall9-FastSwitchPlayerViewInRadar-1.3.2
Backrooms-Backrooms-0.1.3
SirTyler-BetterTeleporter-1.2.2
HolographicWings-LethalExpansion-1.3.22
ViViKo-AllTheScrap-1.0.1
Sv_Matt-HideModList-1.0.1
Ozone-Runtime_Netcode_Patcher-0.2.5
TanmanG-Forest_Giant_Motionsense-1.0.2
mrov-LethalRichPresence-0.5.7
axd1x8a-LCAmmoCheck-1.1.1
PC-FireExitFlip-1.0.0
Toskan4134-LethalRegeneration-1.2.0
TheBeeTeam-LandmineFix-1.0.1
goblinfiend-PlushiesPlus-3.1.0
NiceHairs-NuclearLib-1.0.4
EliteMasterEric-Coroner-1.5.3
2018-Brutal_Company_Reborn-2.1.1
TwinDimensionalProductions-CoilHeadStare-1.0.3
FutureSavior-Hold_Scan_Button-1.1.1
Nebulaetrix-BetterPresents-1.0.3
Rattenbonkers-TVLoader-1.1.1
FlipMods-MoreBlood-1.0.2
monkes_mods-JumpDelayPatch-1.0.1
ATK-ShipClock-0.9.0
FlipMods-LetMeLookDown-1.0.1
tinyhoot-ShipLoot-1.0.0
notnotnotswipez-MoreCompany-1.7.6
EliteMasterEric-WackyCosmetics-2.0.0
NiaNation-AbsasCosmetics-1.2.3
BatTeam-LethalFashion-1.0.6
x753-More_Suits-1.4.1
Verity-TooManySuits-1.0.5
happyfrosty-FrostySuits-1.1.10
sunnobunno-LandMineFartReverb-1.0.3
sunnobunno-BonkHitSFX-1.0.5
rafl-BonkHitSfxFixed-1.0.2
Hexnet111-SuitSaver-1.1.4
Spright-HEV_Yellow-1.0.0
Spright-HEV_Red-1.0.0
Spright-HEV_Purple-1.0.0
Spright-HEV_Black-1.0.0
Spright-HEV_Blue-1.0.1
Spright-HEV_White-1.0.1
Spright-HEV_Green-1.0.0
Dunn-HEV_Suit-1.2.0
fizzysaur-Happy_Hats-2.0.0
Norman-GlowStickSuits-1.0.4
SteamBlizzard-Tyler1Bracken-1.1.0
MagicalFlyingPurpleTreeSquid-Drive_Suit-1.0.3
ViViKo-TrophySuit-1.0.2
ViViKo-MedicSuit-1.0.2
ViViKo-AmongUsSuits-1.0.2
MetalPipeSFX-HornMoan-2.1.0
TopraksuK-FreeBirdTotemRemixJester-1.0.1
DCBlack-Ghost_Buster_Uniform-1.1.5
ColtG5-CreepyBrackens-1.0.2
PoshDonut-PimpAhhSkins-1.2.0
xenertic-YippeeSuit-1.0.0
Festive_Arms-FNAF_Suits-2.0.0
ViViKo-MoreMaterials-1.3.1
ViViKo-AnimatedSuits-1.2.0
ViViKo-BreakingBadHazmatSuit-1.0.3
Regretti-ClassicDoomguy-1.0.0
Flamango-OmniMan_Base_Suits-1.0.0
QuFix-Lidl_Suit-1.0.4
TeamClark-SCP_Foundation_Suit-1.1.0
FlipMods-TooManyEmotes-1.8.1
Mhz-MoreHead-1.2.5
SpookyDookies-Spooky_Dookies_Glowsuits-1.1.8
Kats-Some_Suits-1.0.6
yeahimliam-Peter_Griffin_Suit-1.0.1
Crab_imitation-Reptilian_Suit-1.0.1
Stoners-SpiderManSuitV2-1.2.0
ExioMadeThis-Ahegao_Suit-1.0.0
ManiaBania-1000_Quota_Stare-1.0.0
TeamClark-RustHazmatSuit-1.0.0
kyxino-LethalUtilities-1.2.21
bigmcnugget-VanillaContentExpansion-0.1.8
LeKAKiD-SignalTranslatorAligner-1.1.0
loaforc-FacilityMeltdown-2.0.2
Dreamweave-CompanyBuildingEnhancements-2.6.0
NotAtomicBomb-TerminalApi-1.5.1
Rozebud-FOV_Adjust-1.1.1
darmuh-darmuhsTerminalStuff-2.2.4
IntegrityChaos-Diversity-1.1.10
kuba6000-LC_Masked_Fix-0.0.2
AgentRev-ShootableMouthDogs-1.0.1
NutNutty-SellTracker-1.2.1
Suskitech-AlwaysHearActiveWalkies-1.4.4
EliteMasterEric-SlimeTamingFix-1.0.2
BlueAmulet-LCBetterClock-1.0.3
Bobbie-FixRPCLag-1.0.1
Electric131-OuijaBoard-1.5.2
Woecust-Immersive_Visor-0.2.1
ViViKo-NoSellLimit-1.0.1
NiceHairs-Symbiosis-1.0.5
akechii-DiscountAlert-2.3.0
Blorb-WeatherMultipliers-1.1.0
KodiCraft-TermSpeak-1.1.0
Piggy-JesterStompShake-1.0.8
egeadam-MoreScreams-1.0.3
linkoid-DissonanceLagFix-1.0.0
itsmeowdev-DoorFix-1.0.0
Monkeytype-HideChat-1.0.0
5Bit-VoiceHUD-1.0.4
HGG-JigglePhysicsPlugin-1.1.2
Sai-SaiCosmetics-1.1.0
fonnymunkey-SimpleHats-1.0.0
Hypick-MoreCosmetics-1.3.0
404_Dom-Doms_Basic_Suit_Colors-1.4.4
CapyCat-Solos_Bodycams-1.0.5
AllToasters-SpectateEnemies-2.2.1
vasanex-ItemQuickSwitch-1.1.0
KennyCreations-NoConsole-1.0.0
Jordo-NeedyCats-1.1.1
IAmBatby-LethalLevelLoader-1.0.7

**Comment by FluffyFishGames** [comment]
Seems like a mod conflict to me, can you find out if any mod in particular is causing this in combination with AC?

**Comment by FluffyFishGames** [comment]
Please remove WeatherMultipliers and Strange Objects and test again.

**Comment by FluffyFishGames** [comment]
Could also be LethalUtilities

**Comment by FluffyFishGames** [comment]
Problem solved. Seems like it was WeatherMultipliers.
