### ISSUE TITLE
Feature Request: Allow for cost customization for ship upgrades and decorations (Vanilla)

### ISSUE THREAD

**Issue by WhisperingR** [FluffyFishGames/AdvancedCompany#80]
Seeing as we already have perfect customization of all equipment, scrap, moons and enemies, I think it's only fitting we give the same treatment to the ship upgrades. 
For me specifically, what makes me want this functionality is to be able to buy the Signal Translator for free, seeing as it's something the GhostCodes mod uses, and as of right now I can't use it until the second quota. Plus, things like the Ship horn are a bit too expensive.

Decoration prices follow the same rationale. Don't want to spend hundreds of credits just to buy funny furniture, when I could be spending that money on equipment instead.

**Comment by FluffyFishGames** [comment]
Added in 149
