### ISSUE TITLE
Error displaying Korean player name broken

### ISSUE THREAD

**Issue by crestudio** [FluffyFishGames/AdvancedCompany#83]
**Description :**
The latest Advanced Company 1.0.148 is experiencing a bug where the player name is not displayed properly. Player names are important information in gameplay, so player names that cannot be read can be confusing.
Advanced Company 1.0.143 correctly displayed the player name in the following cases.
- Disabled NameplateTweaks & Disabled FontPatcher
- Enabled NameplateTweaks & Enabled FontPatcher

In the latest version, any action at the top will cause the same problem.

**Reproduction :**
1. Install Lethal Company Korean Patch
2. Install Advanced Company
3. Launch game
4. Korean Steam Nickname player joins lobby

**Expected :**
Korean player names displayed normally.

**Screenshots :**
![20240203175116_1](https://github.com/FluffyFishGames/AdvancedCompany/assets/12029391/01b73b46-29dc-494a-9cee-783a73c431ff)
Original player name : ``거기 라임챤 이리로 오다``

**Context :**
Since the Advanced Company modifies many factors including UI and the implementation varies according to the update of the corresponding mode version, I think the Advanced Company needs to consider it.

**Logfiles :**
- None

**Installed Mods :**
- Lethal Company Korean Patch ( Reference : https://gall.dcinside.com/mgallery/board/view/?id=lethalcompany&no=7 / Direct Download Link : https://drive.google.com/file/d/1bi4bRdLbeEYLRRshon0FuLjjiefCR10L/view?usp=sharing )
- NameplateTweaks
- FontPatcher
- r2modman Mod Profile code : 018d68c1-a504-fb88-c714-a77a227dd766

**Comment by FluffyFishGames** [comment]
Thats funny. Yea, I can change that for 149 hopefully.
