### ISSUE TITLE
Perks Disappeared

### ISSUE THREAD

**Issue by MrRevengeRR** [FluffyFishGames/AdvancedCompany#85]
I have added a few mods to my modpack and suddenly the perks have disappeared completely, writing "perks" in the terminal doesn't even work anymore and the xp is not displayed in the top right corner anymore. I have also removed the new mods and the problem still persists.

[Logs here](https://github.com/FluffyFishGames/AdvancedCompany/files/14154389/Player.log)

Mod List: 
BepInEx-BepInExPack-5.4.2100
notnotnotswipez-MoreCompany-1.7.6
OrtonLongGaming-FreddyBracken-1.0.6
RugbugRedfern-Skinwalkers-4.0.1
x753-Mimics-2.3.2
Ozone-Runtime_Netcode_Patcher-0.2.5
Sligili-More_Emotes-1.3.3
x753-More_Suits-1.4.1
RickArg-Helmet_Cameras-2.1.5
Suskitech-AlwaysHearActiveWalkies-1.4.4
FlipMods-ReservedItemSlotCore-1.8.17
FlipMods-ReservedWalkieSlot-1.6.2
PotatoePet-AdvancedCompany-1.0.148
PopleZoo-BetterItemScan-3.0.1
Verity-TooManySuits-1.0.5
HolographicWings-LethalExpansion-1.3.25
jockie-LethalExpansionCore-1.3.15
sfDesat-Orion-1.3.0
no00ob-LCSoundTool-1.5.1
Clementinise-CustomSounds-2.3.2
funny-HolyMoly-0.0.4
noxitt-NeedMoreBullets-1.0.3
Evaisa-HookGenPatcher-0.0.5
Evaisa-LethalLib-0.14.2
rileyzzz-Skibidi_Toilet-1.0.2
PartyRockers-LethalSlots-1.1.0
NotAtomicBomb-TerminalApi-1.5.1
BGN-PizzaTowerEscapeMusic-2.3.0
loaforc-FacilityMeltdown-2.1.1
LethalResonance-LETHAL_RESONANCE_MELTDOWN-1.1.5
JunLethalCompany-GamblingMachineAtTheCompany-1.3.5
HomelessGinger-MaskedEnemyOverhaul-3.1.2
Evaisa-LethalThings-0.9.4
anormaltwig-LateCompany-1.0.11
malco-Lategame_Upgrades-3.1.1
Rune580-LethalCompany_InputUtils-0.6.2
Renegades-WalkieUse-1.5.0
KoderTeh-Boombox_Controller-1.1.9
IAmBatby-LethalLevelLoader-1.0.7
Badham_Mods-SCPFoundationDungeon-2.3.1
Blorb-WeatherMultipliers-1.1.0
amnsoft-EmployeeAssignments-1.1.0
MegaPiggy-BuyableShotgunShells-1.0.5
MegaPiggy-BuyableShotgun-1.0.4
Midge-PushCompany-1.2.0
sapphlre-randommetalpipe-1.0.2
G7Exid-BikiniBottom-1.2.1
NoahVanilla-dust2-1.0.0
ro-uniforme_romanesti-1.0.0
sfDesat-ExpansionAssets-1.1.0

**Comment by timm0e** [comment]
We also ran into this, but it's just that the perks have been moved to the portable terminal (opened using X per default)

See #9

**Comment by FluffyFishGames** [comment]
Exactly. Its on the portable terminal (default key X)
