### ISSUE TITLE
Suggestion: Stub for legacy perks command

### ISSUE THREAD

**Issue by timm0e** [FluffyFishGames/AdvancedCompany#88]
There have been multiple issues caused by players not being aware that the perks have been moved to the portable terminal

Would it be possible to add a simple stub `perks` command to the ship's terminal that just tells the player perks have been moved (and that they should take a look at the Changelog/README for more changes)? 

Not sure if there's still a horde of new issues coming in, but this might prevent further issues from being created.

Cheers, and thank you for your work!

**Comment by FluffyFishGames** [comment]
Added in 149
