### ISSUE TITLE
Clash between AC's "Save Loot" and LGU's "Scrap Insurance" patches

### ISSUE THREAD

**Issue by WhiteSpike** [FluffyFishGames/AdvancedCompany#89]
## Mod versions
- AdvancedCompany Version: v1.0.148
- Incompatible Mod(s): Lategame Upgrades v3.1.1

## Issues that arise between the mentioned mods and AC
- When a player decides to buy "Scrap Insurance" (which grants a 100% chance of not losing scrap in the next moon landing after a full team wipe and immediately expires after coming back to orbit) and a full team wipe occurs, the player will see their scrap items stored in the ship cleared instead of staying.

## Step guide to cause the issue
- Enter a game
- Acquire some scrap inside the ship (through debug or normal means, it does not influence the result)
- Acquire LGU's Scrap Insurance
- For better clarity of the issue, leave AC's Save Loot at level zero (this will give us a 0% chance of not keeping the scrap item from this perk)
- Land on a moon
- Cause a full team wipe
- Even though LGU's Scrap Insurance was purchased, none of the previously acquired scrap items will be present in the ship.

## Possible causes of the issues
- For the case of Save Loot, a patch is made in ``RoundManager.DespawnPropsAtEndOfRound`` which is a ``prefix`` patch. Most of the code is similar to vanila besides the addition of a random initialized and then compared to Save Loot's multiplier to know if it deletes the scrap or not. After this, it returns false, preventing the vanila code from executing. LGU's Scrap Insurance patch is also on the same function but its through a ``transpiler`` which adds a bool check in essentialy the same place as SaveLoot's comparision. Since the AC's prefix patch returns false in the case of a full team wipe, LGU's transpiler will never reflect an effect, rendering it useless to the eyes of the player.

## Possible solutions/suggestions:
- Instead of a ``prefix`` patch, use a ``transpiler`` instead to add the bool check. This would require the random initialized at some other point (maybe in the same ``prefix`` patch) which is then used in the ``transpiler`` for the comparision with Save Loot's multiplier. This would allow cases of having multiple chances with any other mods that also provide a chance of not losing the scrap (even if not wished for) instead of only one applying and any others are ignored without some sort of heads up.

**Comment by FluffyFishGames** [comment]
Changed it to a transpiler. Fixed in 149
