### ISSUE TITLE
Teleport feature from EnhancedRadarBooster non-functional when paired with AdvancedCompany

### ISSUE THREAD

**Issue by ManaStar** [FluffyFishGames/AdvancedCompany#90]
Version is 1.0.148.

When attempting to teleport the Radar Booster back while paired with [EnhancedRadarBooster](https://thunderstore.io/c/lethal-company/p/MrHydralisk/EnhancedRadarBooster/) the radar booster isn't teleported back and a null error is thrown in console.

**Comment by FluffyFishGames** [comment]
Will probably be fixed in 149
