### ISSUE TITLE
Tactical Helmet Running out of Battery but the Light Still on (Still happening in AC v1.1.1)

### ISSUE THREAD

**Issue by Yumekkiko** [FluffyFishGames/AdvancedCompany#95]
**Describe the bug**
As the title suggests, when a tactical helmet has run out of battery, if the light is on before running out of battery, the light will be still on even after running out of battery. At this moment, even if you press F the light won't be off. But if you drop it down, it will be off.

**To Reproduce**
1. Start the game real quick (maybe change the start credit to buy stuff)
2. Go to Company Building and buy a tactical helmet
3. Toggle the light on and just wait until it runs out of battery
4. Light's still on even if running out of battery

**Expected behavior**
Light should be off after running of battery

**Screenshots**
![LC01](https://github.com/FluffyFishGames/AdvancedCompany/assets/159232068/41616c7a-f71c-4502-8bf2-fb41384e9bc2)

**Additional context**
I don't know why but the log output suggests something's wrong with walkie-talkie function.
PS: don't mind my name being 口口口 in game. I just didn't install Chinese Localization in my testing.

**Logfiles**
[LogOutput.log](https://github.com/FluffyFishGames/AdvancedCompany/files/14190551/LogOutput.log)

**Add a list of all of your mods**
it's manually installed.
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.3
PotatoePet-AdvancedCompany-1.0.149

**Comment by FluffyFishGames** [comment]
Is this error still happening in the latest versions? I close this ticket as I tested it fixed but maybe its broken again?

**Comment by Yumekkiko** [comment]
ohhh, thanks for the heads up. haven't played LC for some time since I'm getting busy. will definitely try it when I get some time. thanks for the hard work of fixing it!
