### ISSUE TITLE
Question About Configuration

### ISSUE THREAD

**Issue by EdahTheRedstoner** [FluffyFishGames/AdvancedCompany#98]
So this is not an issue, more of a question as the settings kinda got me confused right now. It's really dumb to come up with this but I've gone a lot of different games and they've all had it differently, so I don't know the proper way to set it up on this.

So when starting up a new save and going to the "Moons" section, when setting the rarity - how does it work?

Is setting the rarity higher make the item more rare or does it make the item more common?

(I'm asking this as **I'll say it again**, I've had games where setting the rarity higher makes the item more rare, and in some games the rarity worked the other way around - setting it higher made the item more rare)

How does this work here?

_I'm quite dumb sometimes..._

**Comment by FluffyFishGames** [comment]
Higher rarity makes it spawn more often. I might rename it to "weight" later.
